server:
  port: ${SERVER_PORT:8082}

spring:
  config:
    import: classpath:emhare-service-foundation.yml
  application:
    name: academic-setup-service
  http:
    serviceclient:
      student-records:
        base-url: lb://student-records-service
      assessment-results:
        base-url: lb://assessment-results-service
  datasource:
    url: ${ACADEMIC_SETUP_DATABASE_URL:jdbc:postgresql://localhost:5433/emhare_academic_setup}
    username: ${EMHARE_SERVICE_DB_USER:emhare_service}
    password: ${EMHARE_SERVICE_DB_PASSWORD:emhare_dev_password}
