package zw.ac.uz.emhare.finance.catalogue;

import java.math.*;
import java.time.Clock;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import zw.ac.uz.emhare.finance.catalogue.FinanceFeeCatalogueContracts.*;
import zw.ac.uz.emhare.finance.payment.ExchangeRate;
import zw.ac.uz.emhare.finance.payment.ExchangeRateRepository;

/** Versioned institutional fee pricing with maker-checker approval and USD rating evidence. @author Tinashe K */
@Service
public class GovernedFinanceFeeCatalogueService {
    private final FinanceFeeCatalogueRepository catalogueRepository;private final FinanceFeeRuleRepository ruleRepository;
    private final FinanceFeeRuleScopeRepository scopeRepository;private final ExchangeRateRepository exchangeRateRepository;private final Clock clock;
    public GovernedFinanceFeeCatalogueService(FinanceFeeCatalogueRepository catalogueRepository,FinanceFeeRuleRepository ruleRepository,
            FinanceFeeRuleScopeRepository scopeRepository,ExchangeRateRepository exchangeRateRepository,Clock clock){this.catalogueRepository=catalogueRepository;this.ruleRepository=ruleRepository;this.scopeRepository=scopeRepository;this.exchangeRateRepository=exchangeRateRepository;this.clock=clock;}
    @Transactional(readOnly=true) public CatalogueRegister register(){return new CatalogueRegister(catalogueRepository.findAllByDeletedAtIsNullOrderByCodeAsc().stream().map(this::view).toList());}
    @Transactional public CatalogueSummary createCatalogue(CreateCatalogue command,UUID actor){catalogueRepository.findByCodeIgnoreCaseAndDeletedAtIsNull(command.code()).ifPresent(existing->{throw new IllegalStateException("Fee catalogue code already exists.");});return view(catalogueRepository.saveAndFlush(new FinanceFeeCatalogue(command.code(),command.name(),command.description(),command.chargeType(),command.receivableAccountCode(),command.revenueAccountCode(),command.taxCode(),actor)));}
    @Transactional public CatalogueSummary moveCatalogue(UUID id,String action,WorkflowDecision command,UUID actor){FinanceFeeCatalogue catalogue=requireCatalogue(id);if("activate".equals(action))catalogue.activate(actor,clock.instant(),command.reason(),command.expectedVersion());else if("retire".equals(action))catalogue.retire(actor,clock.instant(),command.reason(),command.expectedVersion());else throw new IllegalArgumentException("Unsupported fee catalogue action.");return view(catalogueRepository.saveAndFlush(catalogue));}
    @Transactional public RuleSummary createRule(UUID catalogueId,CreateRule command,UUID actor){FinanceFeeCatalogue catalogue=requireCatalogue(catalogueId);if(catalogue.getStatus()==FinanceFeeCatalogue.Status.RETIRED)throw new IllegalStateException("Retired fee catalogues cannot receive new pricing rules.");validateUniqueDimensions(command.scopes());int nextVersion=ruleRepository.findFirstByFeeCatalogueIdAndDeletedAtIsNullOrderByRuleVersionDesc(catalogueId).map(rule->rule.getRuleVersion()+1).orElse(1);RatedPrice rated=rate(command.transactionAmount(),command.transactionCurrencyCode(),command.effectiveFrom());FinanceFeeRule rule=ruleRepository.saveAndFlush(new FinanceFeeRule(catalogue,nextVersion,command.transactionCurrencyCode(),command.transactionAmount(),rated.exchangeRate(),rated.baseAmount(),command.effectiveFrom(),command.effectiveUntil(),actor));scopeRepository.saveAllAndFlush(command.scopes().stream().map(scope->new FinanceFeeRuleScope(rule,scope.scopeDimension(),scope.referenceId(),scope.referenceCode(),scope.referenceName())).toList());return ruleView(rule);}
    @Transactional public RuleSummary applyRate(UUID ruleId,long expectedVersion){FinanceFeeRule rule=requireRule(ruleId);RatedPrice rated=rate(rule.getTransactionAmount(),rule.getTransactionCurrencyCode(),rule.getEffectiveFrom());if(rated.exchangeRate()==null)throw new IllegalStateException("No active exchange rate is effective for this fee rule start time.");rule.applyRate(rated.exchangeRate(),rated.baseAmount(),expectedVersion);return ruleView(ruleRepository.saveAndFlush(rule));}
    @Transactional public RuleSummary moveRule(UUID id,String action,WorkflowDecision command,UUID actor){FinanceFeeRule rule=requireRule(id);if("approve".equals(action)){List<FinanceFeeRuleScope> scopes=scopes(id);if(scopes.isEmpty())throw new IllegalStateException("Fee rule requires at least one explicit scope.");String signature=scopes.stream().map(FinanceFeeRuleScope::canonicalPart).sorted().reduce((left,right)->left+"|"+right).orElseThrow();rule.approve(actor,clock.instant(),command.reason(),signature,command.expectedVersion());}else if("retire".equals(action))rule.retire(actor,clock.instant(),command.reason(),command.expectedVersion());else throw new IllegalArgumentException("Unsupported fee rule action.");return ruleView(ruleRepository.saveAndFlush(rule));}
    private RatedPrice rate(BigDecimal amount,String currencyCode,java.time.Instant effectiveAt){String currency=ExchangeRate.normalizeCurrencyCode(currencyCode);if("USD".equals(currency))return new RatedPrice(null,amount);List<ExchangeRate> rates=exchangeRateRepository.findEffectiveRates(currency,effectiveAt);if(rates.size()>1)throw new IllegalStateException("Multiple effective exchange rates require Finance correction before pricing.");if(rates.isEmpty())return new RatedPrice(null,null);ExchangeRate rate=rates.getFirst();return new RatedPrice(rate,amount.multiply(rate.getRateToBase()).setScale(2,RoundingMode.HALF_UP));}
    private void validateUniqueDimensions(List<ScopeInput> scopes){long unique=scopes.stream().map(ScopeInput::scopeDimension).distinct().count();if(unique!=scopes.size())throw new IllegalArgumentException("A fee rule can contain each scope dimension only once.");if(scopes.stream().anyMatch(scope->scope.scopeDimension()==FinanceFeeRuleScope.Dimension.GLOBAL)&&scopes.size()>1)throw new IllegalArgumentException("Global scope cannot be combined with another fee scope.");}
    private FinanceFeeCatalogue requireCatalogue(UUID id){return catalogueRepository.findLockedByIdAndDeletedAtIsNull(id).orElseThrow(()->new IllegalArgumentException("Fee catalogue was not found."));}
    private FinanceFeeRule requireRule(UUID id){return ruleRepository.findLockedByIdAndDeletedAtIsNull(id).orElseThrow(()->new IllegalArgumentException("Fee rule was not found."));}
    private List<FinanceFeeRuleScope> scopes(UUID ruleId){return scopeRepository.findAllByFeeRuleIdAndDeletedAtIsNullOrderByScopeDimensionAsc(ruleId);}
    private CatalogueSummary view(FinanceFeeCatalogue catalogue){return new CatalogueSummary(catalogue.getId(),catalogue.getCode(),catalogue.getName(),catalogue.getDescription(),catalogue.getChargeType(),catalogue.getReceivableAccountCode(),catalogue.getRevenueAccountCode(),catalogue.getTaxCode(),catalogue.getBaseCurrencyCode(),catalogue.getStatus(),catalogue.getPreparedByUserId(),catalogue.getActivatedByUserId(),catalogue.getActivatedAt(),catalogue.getVersion(),ruleRepository.findAllByFeeCatalogueIdAndDeletedAtIsNullOrderByRuleVersionDesc(catalogue.getId()).stream().map(this::ruleView).toList());}
    private RuleSummary ruleView(FinanceFeeRule rule){return new RuleSummary(rule.getId(),rule.getRuleVersion(),rule.getTransactionCurrencyCode(),rule.getTransactionAmount(),rule.getBaseCurrencyCode(),rule.getExchangeRate()==null?null:rule.getExchangeRate().getId(),rule.getBaseAmount(),rule.getRatingStatus(),rule.getEffectiveFrom(),rule.getEffectiveUntil(),rule.getScopeSignature(),rule.getStatus(),rule.getPreparedByUserId(),rule.getApprovedByUserId(),rule.getApprovedAt(),rule.getVersion(),scopes(rule.getId()).stream().map(scope->new ScopeSummary(scope.getId(),scope.getScopeDimension(),scope.getReferenceId(),scope.getReferenceCode(),scope.getReferenceName())).toList());}
    private record RatedPrice(ExchangeRate exchangeRate,BigDecimal baseAmount) {}
}
