<script setup lang="ts">
import Swal from 'sweetalert2'
import type { ExamSetupRegister, ExamTimetableRunSummary, ExamTimetableStatus } from '@emhare/portal-shell/types/exams'

definePageMeta({ layout: 'dashboard' })
const api = useEmhareApi(); const toast = useToast(); const { showError } = useEmhareConfirm()
const academicPeriodContext = useAcademicPeriodContext()
const runs = ref<ExamTimetableRunSummary[]>([]); const setup = ref<ExamSetupRegister>({ venueTypes: [], venues: [], sessions: [], requirements: [] })
const loading = ref(false); const generating = ref(false); const actingRunId = ref<string | null>(null); const generateModalOpen = ref(false); const selectedSessionId = ref('')
const statusFilter = ref<'ALL' | ExamTimetableStatus>('ALL'); const search = ref('')
const sessionItems = computed(() => setup.value.sessions.filter(item => item.status === 'APPROVED').map(item => ({ label: `${item.academicPeriodCode} · ${item.code} · ${item.name}`, value: item.id })))
const counts = computed(() => ({ total: runs.value.length, review: runs.value.filter(item => item.status === 'GENERATED' || item.status === 'REVIEWED').length, approved: runs.value.filter(item => item.status === 'APPROVED').length, published: runs.value.filter(item => item.status === 'PUBLISHED').length }))
const visibleRuns = computed(() => { const query = search.value.trim().toLowerCase(); return runs.value.filter(item => (statusFilter.value === 'ALL' || item.status === statusFilter.value) && (!query || [item.runNumber, item.sessionCode, item.sessionName].some(value => value.toLowerCase().includes(query)))) })
onMounted(load)
watch(academicPeriodContext.selectedAcademicPeriodId, () => { selectedSessionId.value = ''; void load() })

async function load() { loading.value = true; try { const [runResponse, setupResponse] = await Promise.all([api.request<ExamTimetableRunSummary[]>('/api/timetabling/runs'), api.request<ExamSetupRegister>('/api/exams/setup')]); const sessions=setupResponse.sessions.filter(session=>academicPeriodContext.matchesAcademicPeriod(session));const sessionIds=new Set(sessions.map(session=>session.id));setup.value={...setupResponse,sessions,requirements:setupResponse.requirements.filter(requirement=>academicPeriodContext.matchesAcademicPeriod(requirement))};runs.value=runResponse.filter(run=>sessionIds.has(run.examSessionId)) } catch (error) { await showError('Exam timetables could not be loaded', api.errorMessage(error)) } finally { loading.value = false } }
async function generate() { if (!selectedSessionId.value) return; const result = await Swal.fire({ title: 'Generate governed timetable?', text: 'Confirmed registration snapshots, approved Module requirements, certified venue availability, capacity, and candidate clashes will be evaluated atomically.', icon: 'question', showCancelButton: true, confirmButtonText: 'Generate timetable', confirmButtonColor: '#006633' }); if (!result.isConfirmed) return; generating.value = true; try { await api.request('/api/timetabling/runs', { method: 'POST', body: { examSessionId: selectedSessionId.value } }); generateModalOpen.value = false; await load(); toast.add({ title: 'Timetable generated', description: 'The complete candidate and venue allocation is ready for independent review.', color: 'success' }) } catch (error) { await showError('Timetable could not be generated', api.errorMessage(error)) } finally { generating.value = false } }
async function move(run: ExamTimetableRunSummary, action: 'review' | 'approve' | 'publish' | 'reject') { const labels = { review: 'Record independent review', approve: 'Approve timetable', publish: 'Publish candidate timetables', reject: 'Reject timetable' }; const descriptions = { review: 'Confirm the clash report, candidate coverage, venue capacity, and allocation evidence.', approve: 'Record examination board or delegated approval. The approver must be independent.', publish: 'Release this immutable timetable to candidate views. The publisher must be a fourth independent actor.', reject: 'Record why this generated timetable cannot proceed.' }; const result = await Swal.fire({ title: `${labels[action]}?`, text: descriptions[action], input: 'textarea', inputLabel: 'Workflow reason', inputPlaceholder: 'Record the operational evidence for this decision.', icon: action === 'reject' ? 'warning' : 'question', showCancelButton: true, confirmButtonText: labels[action], confirmButtonColor: action === 'reject' ? '#b91c1c' : '#006633', inputValidator: value => value.trim() ? undefined : 'A workflow reason is required.' }); if (!result.isConfirmed || !result.value?.trim()) return; actingRunId.value = run.id; try { await api.request(`/api/timetabling/runs/${run.id}/${action}`, { method: 'POST', body: { reason: result.value.trim(), expectedVersion: run.version } }); await load(); toast.add({ title: `${labels[action]} completed`, color: 'success' }) } catch (error) { await showError(`${labels[action]} failed`, api.errorMessage(error)) } finally { actingRunId.value = null } }
function statusColour(status: ExamTimetableStatus) { if (status === 'PUBLISHED') return 'success'; if (status === 'REJECTED') return 'error'; if (status === 'APPROVED') return 'primary'; return 'warning' }
function timestamp(value: string) { return new Intl.DateTimeFormat('en-ZW', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
</script>

<template>
  <UDashboardPanel>
    <template #header><UDashboardNavbar title="Exam timetable control"><template #leading><UDashboardSidebarCollapse /></template><template #right><UButton label="Generate timetable" icon="i-lucide-calendar-cog" @click="generateModalOpen = true" /><UButton label="Refresh" icon="i-lucide-refresh-cw" color="neutral" variant="outline" :loading="loading" @click="load" /></template></UDashboardNavbar></template>
    <template #body><div class="space-y-5 p-4 sm:p-6">
      <UAlert color="primary" variant="soft" icon="i-lucide-shield-check" title="Candidate-safe timetable governance" description="Generation is atomic: no partial schedule is retained when a Module lacks an approved requirement, clash-free slot, certified venue type, availability, or capacity. Review, approval, and publication require independent operators." />
      <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><UCard :ui="{ body: 'p-4' }"><p class="text-xs uppercase text-muted">Generation runs</p><p class="mt-2 text-2xl font-semibold">{{ counts.total }}</p></UCard><UCard :ui="{ body: 'p-4' }"><p class="text-xs uppercase text-warning">Review queue</p><p class="mt-2 text-2xl font-semibold">{{ counts.review }}</p></UCard><UCard :ui="{ body: 'p-4' }"><p class="text-xs uppercase text-primary">Awaiting publication</p><p class="mt-2 text-2xl font-semibold">{{ counts.approved }}</p></UCard><UCard :ui="{ body: 'p-4' }"><p class="text-xs uppercase text-success">Published</p><p class="mt-2 text-2xl font-semibold">{{ counts.published }}</p></UCard></section>
      <UCard :ui="{ body: 'p-4' }"><div class="grid gap-3 sm:grid-cols-[1fr_220px]"><UInput v-model="search" icon="i-lucide-search" placeholder="Search run or exam session" /><USelect v-model="statusFilter" :items="[{ label: 'All statuses', value: 'ALL' }, { label: 'Generated', value: 'GENERATED' }, { label: 'Reviewed', value: 'REVIEWED' }, { label: 'Approved', value: 'APPROVED' }, { label: 'Published', value: 'PUBLISHED' }, { label: 'Rejected', value: 'REJECTED' }]" /></div></UCard>
      <EmharePaginatedCollection :items="visibleRuns" v-slot="{ items: paginatedRuns }"><div class="space-y-4"><UCard v-for="run in paginatedRuns" :key="run.id" :ui="{ body: 'p-4 sm:p-5' }">
        <div class="flex flex-wrap items-start justify-between gap-3"><div><p class="font-mono text-xs text-primary">{{ run.runNumber }}</p><h2 class="mt-1 text-lg font-semibold">{{ run.sessionCode }} · {{ run.sessionName }}</h2><p class="mt-1 text-sm text-muted">Generated {{ timestamp(run.generatedAt) }} · deterministic policy {{ run.generationPolicy.algorithm }}</p></div><UBadge :label="run.status" :color="statusColour(run.status)" variant="subtle" /></div>
        <div class="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><div class="rounded-md border border-muted p-3"><p class="text-xs text-muted">Candidates</p><p class="mt-1 text-xl font-semibold">{{ run.candidateCount }}</p></div><div class="rounded-md border border-muted p-3"><p class="text-xs text-muted">Modules scheduled</p><p class="mt-1 text-xl font-semibold">{{ run.timetableEntryCount }}/{{ run.moduleCount }}</p></div><div class="rounded-md border border-muted p-3"><p class="text-xs text-muted">Detected clashes</p><p class="mt-1 text-xl font-semibold" :class="run.conflictCount ? 'text-error' : 'text-success'">{{ run.conflictCount }}</p></div><div class="rounded-md border border-muted p-3"><p class="text-xs text-muted">Optimistic version</p><p class="mt-1 text-xl font-semibold">{{ run.version }}</p></div></div>
        <EmharePaginatedCollection :items="run.entries" v-slot="{ items: paginatedEntries }"><div class="mt-4 overflow-x-auto rounded-lg border border-muted"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-muted/40 text-xs uppercase text-muted"><tr><th class="px-3 py-2">Module</th><th class="px-3 py-2">Candidate count</th><th class="px-3 py-2">Window</th><th class="px-3 py-2">Venue allocation</th></tr></thead><tbody><tr v-for="entry in paginatedEntries" :key="entry.id" class="border-t border-muted"><td class="px-3 py-3"><p class="font-medium">{{ entry.moduleCode }}</p><p class="text-xs text-muted">{{ entry.moduleName }}</p></td><td class="px-3 py-3">{{ entry.candidateCount }}</td><td class="px-3 py-3"><p>{{ entry.slotCode }}</p><p class="text-xs text-muted">{{ timestamp(entry.startsAt) }} – {{ timestamp(entry.endsAt) }}</p></td><td class="px-3 py-3"><div class="flex flex-wrap gap-1"><UBadge v-for="venue in entry.venues" :key="venue.id" :label="`${venue.venueCode} · ${venue.allocatedCapacity}`" color="neutral" variant="outline" /></div></td></tr></tbody></table></div></EmharePaginatedCollection>
        <div class="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-muted pt-4"><p class="text-xs text-muted">Generator {{ run.generatedByUserId }}<span v-if="run.reviewedByUserId"> · reviewer {{ run.reviewedByUserId }}</span><span v-if="run.approvedByUserId"> · approver {{ run.approvedByUserId }}</span><span v-if="run.publishedByUserId"> · publisher {{ run.publishedByUserId }}</span></p><div class="flex flex-wrap gap-2"><UButton v-if="run.status === 'GENERATED'" label="Review" icon="i-lucide-search-check" :loading="actingRunId === run.id" @click="move(run, 'review')" /><UButton v-if="run.status === 'REVIEWED'" label="Approve" icon="i-lucide-badge-check" :loading="actingRunId === run.id" @click="move(run, 'approve')" /><UButton v-if="run.status === 'APPROVED'" label="Publish" icon="i-lucide-send" :loading="actingRunId === run.id" @click="move(run, 'publish')" /><UButton v-if="!['PUBLISHED','REJECTED'].includes(run.status)" label="Reject" icon="i-lucide-circle-x" color="error" variant="soft" :loading="actingRunId === run.id" @click="move(run, 'reject')" /></div></div>
      </UCard></div></EmharePaginatedCollection>
      <UAlert v-if="!loading && !visibleRuns.length" color="neutral" variant="soft" title="No timetable runs match" description="Generate a run only after the exam session, slots, Module requirements, venue capacity, and availability are approved." />
    </div></template>
  </UDashboardPanel>
  <EmhareRecordDrawer v-model:open="generateModalOpen" title="Generate exam timetable" description="Choose an approved exam session. Generation uses all eligible confirmed registrations in its academic period."><template #body><div class="space-y-4"><UFormField label="Approved exam session" required><USelect v-model="selectedSessionId" :items="sessionItems" class="w-full" placeholder="Select session" /></UFormField><UAlert color="info" variant="soft" title="All-or-nothing generation" description="If any Module cannot be placed without a candidate clash or complete certified venue capacity, the transaction is rolled back and no partial run is retained." /></div></template><template #footer><div class="flex w-full justify-end gap-2"><UButton label="Cancel" color="neutral" variant="outline" @click="generateModalOpen = false" /><EmhareGuidedActionButton label="Generate timetable" icon="i-lucide-calendar-cog" :loading="generating" guidance-title="Select an exam session" :guidance-instructions="selectedSessionId ? [] : ['Select an approved exam session before generating its timetable.']" @click="generate" /></div></template></EmhareRecordDrawer>
</template>
