CREATE TABLE revinfo (
    rev integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp bigint NOT NULL,
    actor_user_id uuid,
    service_name varchar(100) NOT NULL DEFAULT 'notifications-service',
    correlation_id varchar(100),
    reason varchar(500)
);
