-- Author: Tinashe K

WITH template_definitions(event_type, code_prefix, name, subject_template, body_template) AS (
    VALUES
        ('APPLICATION_SUBMITTED', 'APPLICATION_SUBMITTED', 'Application submitted',
            'Application {{applicationNumber}} submitted',
            'Dear {{firstName}}, your application {{applicationNumber}} has been submitted successfully.'),
        ('MISSING_DOCUMENTS', 'MISSING_DOCUMENTS', 'Missing application documents',
            'Documents required for application {{applicationNumber}}',
            'Dear {{firstName}}, application {{applicationNumber}} requires the following documents: {{documentList}}.'),
        ('PAYMENT_CONFIRMED', 'PAYMENT_CONFIRMED', 'Application payment confirmed',
            'Payment confirmed for application {{applicationNumber}}',
            'Dear {{firstName}}, payment reference {{paymentReference}} for application {{applicationNumber}} has been confirmed.'),
        ('VERIFICATION_DECISION', 'VERIFICATION_DECISION', 'Application verification decision',
            'Application {{applicationNumber}} verification update',
            'Dear {{firstName}}, application {{applicationNumber}} now has verification status {{decision}}.'),
        ('OFFER_DISPATCHED', 'OFFER_DISPATCHED', 'Admission offer dispatched',
            'Admission offer {{offerNumber}}',
            'Dear {{firstName}}, offer {{offerNumber}} for {{programmeName}} is available. Respond by {{acceptanceDeadline}}.'),
        ('OFFER_RESPONSE', 'OFFER_RESPONSE', 'Admission offer response',
            'Offer {{offerNumber}} response recorded',
            'Dear {{firstName}}, your {{response}} response to offer {{offerNumber}} has been recorded.'),
        ('STUDENT_CONVERSION', 'STUDENT_CONVERSION', 'Student conversion completed',
            'Student record {{studentNumber}} created',
            'Dear {{firstName}}, your student record {{studentNumber}} for {{programmeName}} has been created.'),
        ('REGISTRATION_ACTION', 'REGISTRATION_ACTION', 'Student registration action',
            'Registration action for {{studentNumber}}',
            'Dear {{firstName}}, registration for {{studentNumber}} requires this action: {{requiredAction}}.'),
        ('WORKFLOW_TASK', 'WORKFLOW_TASK', 'Operational workflow task',
            'Workflow task {{taskReference}}',
            '{{taskTitle}} requires action by {{dueAt}}. Reference: {{taskReference}}.')
),
channels(channel) AS (
    VALUES ('EMAIL'), ('IN_APP')
)
INSERT INTO notification_templates (
    id,
    code,
    template_version,
    name,
    event_type,
    channel,
    category,
    locale,
    subject_template,
    body_template,
    status,
    prepared_by_user_id,
    approved_by_user_id,
    approved_at,
    approval_reason,
    created_at,
    updated_at,
    created_by_user_id,
    modified_by_user_id,
    version)
SELECT
    md5(definition.code_prefix || ':' || channel.channel)::uuid,
    definition.code_prefix || '_' || channel.channel,
    1,
    definition.name || CASE channel.channel WHEN 'EMAIL' THEN ' email' ELSE ' in-app' END,
    definition.event_type,
    channel.channel,
    'TRANSACTIONAL',
    'en-ZW',
    definition.subject_template,
    definition.body_template,
    'ACTIVE',
    '00000000-0000-0000-0000-000000000001'::uuid,
    '00000000-0000-0000-0000-000000000002'::uuid,
    CURRENT_TIMESTAMP,
    'Approved baseline transactional template for required ERP workflow notifications.',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    '00000000-0000-0000-0000-000000000001'::uuid,
    '00000000-0000-0000-0000-000000000002'::uuid,
    0
FROM template_definitions definition
CROSS JOIN channels channel;
