-- Author: Tinashe K

INSERT INTO notification_templates (
    id,
    code,
    template_version,
    name,
    event_type,
    channel,
    category,
    locale,
    subject_template,
    body_template,
    status,
    prepared_by_user_id,
    approved_by_user_id,
    approved_at,
    approval_reason,
    created_at,
    updated_at,
    created_by_user_id,
    modified_by_user_id,
    version)
VALUES (
    md5('REFEREE_REFERENCE_REQUEST_EMAIL:1')::uuid,
    'REFEREE_REFERENCE_REQUEST_EMAIL',
    1,
    'Postgraduate referee reference request email',
    'REFEREE_REFERENCE_REQUEST',
    'EMAIL',
    'TRANSACTIONAL',
    'en-ZW',
    'Reference request for {{applicantName}} ({{applicationNumber}})',
    'Dear {{refereeName}}, {{applicantName}} has nominated you as a referee for {{applicationTypeName}} application {{applicationNumber}}. Please provide your confidential reference by {{expiresAt}} using this secure link: {{responseUrl}}',
    'ACTIVE',
    '00000000-0000-0000-0000-000000000001'::uuid,
    '00000000-0000-0000-0000-000000000002'::uuid,
    CURRENT_TIMESTAMP,
    'Approved transactional template for applicant-nominated postgraduate referee requests.',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    '00000000-0000-0000-0000-000000000001'::uuid,
    '00000000-0000-0000-0000-000000000002'::uuid,
    0
);
