package zw.ac.uz.emhare.notifications;

import zw.ac.uz.emhare.notifications.domain.model.InAppNotification;
import zw.ac.uz.emhare.notifications.domain.model.NotificationConsent;
import zw.ac.uz.emhare.notifications.domain.model.NotificationDeliveryAttempt;
import zw.ac.uz.emhare.notifications.domain.model.NotificationEventInbox;
import zw.ac.uz.emhare.notifications.domain.model.NotificationProviderCallback;
import zw.ac.uz.emhare.notifications.domain.model.NotificationRequest;
import zw.ac.uz.emhare.notifications.domain.model.NotificationTemplate;
import zw.ac.uz.emhare.notifications.domain.model.NotificationValues;
import zw.ac.uz.emhare.notifications.infrastructure.persistence.InAppNotificationRepository;
import zw.ac.uz.emhare.notifications.infrastructure.persistence.NotificationConsentRepository;
import zw.ac.uz.emhare.notifications.infrastructure.persistence.NotificationDeliveryAttemptRepository;
import zw.ac.uz.emhare.notifications.infrastructure.persistence.NotificationEventInboxRepository;
import zw.ac.uz.emhare.notifications.infrastructure.persistence.NotificationProviderCallbackRepository;
import zw.ac.uz.emhare.notifications.infrastructure.persistence.NotificationRequestRepository;
import zw.ac.uz.emhare.notifications.infrastructure.persistence.NotificationTemplateRepository;
import zw.ac.uz.emhare.notifications.infrastructure.persistence.NotificationRequestAttachmentRepository;
import zw.ac.uz.emhare.notifications.domain.model.NotificationRequestAttachment;

import java.time.*;
import java.util.*;
import java.util.regex.*;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.PageRequest;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import zw.ac.uz.emhare.notifications.api.model.NotificationApiModels.*;

/** @author Tinashe K */
@Service
public class NotificationService {
    private static final Pattern TOKEN=Pattern.compile("\\{\\{([A-Za-z][A-Za-z0-9_.-]{0,79})}}" );
    private final NotificationTemplateRepository templates; private final NotificationConsentRepository consents; private final NotificationRequestRepository requests; private final NotificationDeliveryAttemptRepository attempts; private final NotificationEventInboxRepository eventInbox; private final NotificationProviderCallbackRepository providerCallbacks; private final InAppNotificationRepository inAppNotifications; private final NotificationRequestAttachmentRepository attachments; private final NotificationDeliveryProvider provider; private final NotificationDeliveryOutboxService deliveryOutbox; private final Clock clock;
    public NotificationService(NotificationTemplateRepository templates,NotificationConsentRepository consents,NotificationRequestRepository requests,NotificationDeliveryAttemptRepository attempts,NotificationEventInboxRepository eventInbox,NotificationProviderCallbackRepository providerCallbacks,InAppNotificationRepository inAppNotifications,NotificationRequestAttachmentRepository attachments,NotificationDeliveryProvider provider,NotificationDeliveryOutboxService deliveryOutbox,Clock clock){this.templates=templates;this.consents=consents;this.requests=requests;this.attempts=attempts;this.eventInbox=eventInbox;this.providerCallbacks=providerCallbacks;this.inAppNotifications=inAppNotifications;this.attachments=attachments;this.provider=provider;this.deliveryOutbox=deliveryOutbox;this.clock=clock;}

    @Transactional(readOnly=true) public Register register(){return new Register(templates.findAllByOrderByCodeAscTemplateVersionDesc().stream().map(this::summary).toList(),consents.findAllByOrderByRecipientKeyAscCategoryAsc().stream().map(this::summary).toList(),requests.findAllByOrderByScheduledAtDesc().stream().map(this::summary).toList(),attempts.findAllByOrderByStartedAtDesc().stream().map(this::summary).toList(),eventInbox.findAllByOrderByReceivedAtDesc().stream().map(this::summary).toList(),providerCallbacks.findAllByOrderByReceivedAtDesc().stream().map(this::summary).toList(),inAppNotifications.findAllByOrderByDeliveredAtDesc().stream().map(this::summary).toList());}
    @Transactional public TemplateSummary createTemplate(CreateTemplate command,UUID actor){return summary(templates.save(new NotificationTemplate(command.code(),command.templateVersion(),command.name(),command.eventType(),command.channel(),command.category(),command.locale(),command.subjectTemplate(),command.bodyTemplate(),actor)));}
    @Transactional public TemplateSummary updateTemplate(UUID id,UpdateTemplate command){NotificationTemplate template=template(id);template.updateDraft(command.name(),command.eventType(),command.category(),command.subjectTemplate(),command.bodyTemplate(),command.expectedVersion());return summary(template);}
    @Transactional public TemplateSummary transitionTemplate(UUID id,TemplateTransition command,UUID actor){NotificationTemplate template=template(id);Instant now=clock.instant();if(command.targetStatus()==NotificationTemplate.Status.ACTIVE)template.activate(actor,command.reason(),now,command.expectedVersion());else if(command.targetStatus()==NotificationTemplate.Status.RETIRED)template.retire(actor,command.reason(),now,command.expectedVersion());else throw new IllegalArgumentException("Notification template target status must be ACTIVE or RETIRED.");return summary(template);}
    @Transactional public ConsentSummary recordConsent(RecordConsent command){Instant now=clock.instant();Optional<NotificationConsent> current=consents.findFirstByRecipientKeyIgnoreCaseAndChannelAndCategoryAndEffectiveUntilIsNull(command.recipientKey(),command.channel(),command.category());if(current.isPresent()){if(command.expectedVersion()==null)throw new IllegalStateException("The current consent version is required when changing an existing preference.");current.get().replace(command.status(),command.source(),command.evidenceReference(),now,command.expectedVersion());return summary(current.get());}return summary(consents.save(new NotificationConsent(command.recipientUserId(),command.recipientKey(),command.channel(),command.category(),command.status(),command.source(),command.evidenceReference(),now)));}
    @Transactional public RequestSummary queue(QueueNotification command){Optional<NotificationRequest> duplicate=requests.findByIdempotencyKey(command.idempotencyKey());if(duplicate.isPresent())return summary(duplicate.get());NotificationTemplate template=templates.findFirstByCodeIgnoreCaseAndChannelAndLocaleAndStatusOrderByTemplateVersionDesc(command.templateCode(),command.channel(),command.locale(),NotificationTemplate.Status.ACTIVE).orElseThrow(()->new IllegalStateException("No active notification template matches the requested code, channel, and locale."));if(!template.getEventType().equals(NotificationValues.code(command.eventType(),"Event type")))throw new IllegalArgumentException("The notification event type does not match the active template.");if(template.getChannel()==NotificationTemplate.Channel.IN_APP&&command.recipientUserId()==null)throw new IllegalArgumentException("In-app notifications require a recipient user ID.");String consentDecision=consentDecision(command.recipientKey(),template);boolean suppressed="OPTED_OUT".equals(consentDecision)||"CONSENT_MISSING".equals(consentDecision);Map<String,String> variables=command.variables()==null?Map.of():command.variables();String subject=render(template.getSubjectTemplate(),variables);String body=render(template.getBodyTemplate(),variables);Instant scheduled=command.scheduledAt()==null?clock.instant():command.scheduledAt();long sequence=requests.nextRequestNumber();NotificationRequest request=new NotificationRequest("NTF-"+String.format("%010d",sequence),command.idempotencyKey(),command.sourceService(),command.sourceEventId(),command.eventType(),template,command.recipientUserId(),command.recipientKey(),command.recipientAddress(),subject,body,command.priority(),consentDecision,scheduled,command.maxAttempts()==null?5:command.maxAttempts(),suppressed);try{request=requests.saveAndFlush(request);java.util.List<zw.ac.uz.emhare.common.messaging.NotificationAttachmentReference> refs=command.attachments()==null?java.util.List.of():command.attachments();for(int index=0;index<refs.size();index++)attachments.save(new NotificationRequestAttachment(request.getId(),index+1,refs.get(index)));return summary(request);}catch(DataIntegrityViolationException conflict){return requests.findByIdempotencyKey(command.idempotencyKey()).map(this::summary).orElseThrow(()->conflict);}}
    @Transactional public RequestSummary retry(UUID id,ManualAction command,UUID actor){NotificationRequest request=request(id);request.retryNow(actor,command.reason(),clock.instant(),command.expectedVersion());return summary(request);}
    @Transactional public RequestSummary cancel(UUID id,ManualAction command,UUID actor){NotificationRequest request=request(id);request.cancel(actor,command.reason(),clock.instant(),command.expectedVersion());return summary(request);}
    @Transactional public void captureEvent(String sourceService,UUID eventId,String eventType,String rawPayload){if(eventInbox.findBySourceServiceIgnoreCaseAndSourceEventId(sourceService,eventId).isPresent())return;eventInbox.saveAndFlush(new NotificationEventInbox(sourceService,eventId,eventType,rawPayload,clock.instant(),10));}
    @Transactional public InboxSummary retryEvent(UUID id,ManualAction command,UUID actor){NotificationEventInbox inbox=eventInbox.findById(id).orElseThrow(()->new NoSuchElementException("Notification event was not found."));inbox.retryNow(actor,command.reason(),clock.instant(),command.expectedVersion());return summary(inbox);}

    @Transactional public CallbackSummary recordProviderCallback(String providerCode,ProviderCallbackPayload command,Map<String,Object> callbackPayload){Optional<NotificationProviderCallback> duplicate=providerCallbacks.findByProviderCodeIgnoreCaseAndProviderEventId(providerCode,command.providerEventId());if(duplicate.isPresent())return summary(duplicate.get());NotificationRequest request=requests.findFirstByProviderCodeIgnoreCaseAndProviderMessageId(providerCode,command.providerMessageId()).orElseThrow(()->new IllegalStateException("The provider message is not yet available for callback reconciliation."));Instant receivedAt=clock.instant();NotificationProviderCallback callback=new NotificationProviderCallback(providerCode,command.providerEventId(),command.providerMessageId(),command.deliveryStatus(),command.occurredAt(),receivedAt,request.getId(),command.errorCode(),command.errorMessage(),callbackPayload);request.applyProviderStatus(providerStatus(command.deliveryStatus()),command.occurredAt(),command.errorMessage());deliveryOutbox.enqueue(request,command.deliveryStatus().name(),command.providerMessageId(),command.errorMessage());try{return summary(providerCallbacks.saveAndFlush(callback));}catch(DataIntegrityViolationException conflict){return providerCallbacks.findByProviderCodeIgnoreCaseAndProviderEventId(providerCode,command.providerEventId()).map(this::summary).orElseThrow(()->conflict);}}
    @Transactional(readOnly=true) public List<InAppSummary> myInAppNotifications(UUID userId){return inAppNotifications.findAllByRecipientUserIdOrderByDeliveredAtDesc(userId).stream().map(this::summary).toList();}
    @Transactional public InAppSummary markInAppRead(UUID notificationId,UUID userId,long expectedVersion){InAppNotification notification=inAppNotifications.findByIdAndRecipientUserId(notificationId,userId).orElseThrow(()->new NoSuchElementException("In-app notification was not found."));notification.markRead(userId,clock.instant(),expectedVersion);return summary(notification);}

    @Scheduled(fixedDelayString="${emhare.notifications.dispatch-interval-ms:5000}")
    @Transactional public void dispatchDue(){Instant now=clock.instant();for(NotificationRequest request:requests.lockDue(now,PageRequest.of(0,50)))dispatch(request,now);}
    void dispatch(NotificationRequest request,Instant started){request.startAttempt();if(request.getChannel()==NotificationTemplate.Channel.IN_APP){dispatchInApp(request,started);return;}NotificationDeliveryProvider.DeliveryResult result;try{result=provider.deliver(request);}catch(RuntimeException exception){result=NotificationDeliveryProvider.DeliveryResult.failed(true,"PROVIDER_EXCEPTION",safeMessage(exception),Map.of());}Instant completed=clock.instant();NotificationDeliveryAttempt.Outcome outcome=result.sent()?NotificationDeliveryAttempt.Outcome.SENT:result.retryable()?NotificationDeliveryAttempt.Outcome.RETRYABLE_FAILURE:NotificationDeliveryAttempt.Outcome.PERMANENT_FAILURE;attempts.save(new NotificationDeliveryAttempt(request.getId(),request.getAttemptCount(),provider.code(),started,completed,outcome,result.providerMessageId(),result.errorCode(),result.errorMessage(),result.metadata()));if(result.sent()){request.sent(provider.code(),result.providerMessageId(),completed);deliveryOutbox.enqueue(request,"SENT",result.providerMessageId(),null);}else{request.deliveryFailed(provider.code(),result.errorCode(),result.errorMessage(),result.retryable(),completed,completed.plusSeconds(Math.min(3600,60L<<(Math.min(request.getAttemptCount()-1,5)))));deliveryOutbox.enqueue(request,"FAILED",null,result.errorMessage());}}
    private void dispatchInApp(NotificationRequest request,Instant started){Instant completed=clock.instant();InAppNotification notification=inAppNotifications.findByNotificationRequestId(request.getId()).orElseGet(()->inAppNotifications.save(new InAppNotification(request,completed)));String messageId="in-app-"+notification.getId();attempts.save(new NotificationDeliveryAttempt(request.getId(),request.getAttemptCount(),"IN_APP",started,completed,NotificationDeliveryAttempt.Outcome.SENT,messageId,null,null,Map.of("delivery","database-inbox")));request.deliveredInApp(messageId,completed);}

    private String consentDecision(String recipientKey,NotificationTemplate template){if(template.getCategory()!=NotificationTemplate.Category.MARKETING)return "NOT_REQUIRED";return consents.findFirstByRecipientKeyIgnoreCaseAndChannelAndCategoryAndEffectiveUntilIsNull(recipientKey,template.getChannel(),template.getCategory()).map(value->value.getStatus()==NotificationConsent.Status.OPTED_IN?"OPTED_IN":"OPTED_OUT").orElse("CONSENT_MISSING");}
    private String render(String template,Map<String,String> values){if(template==null)return null;Matcher matcher=TOKEN.matcher(template);StringBuilder rendered=new StringBuilder();while(matcher.find()){String value=values.get(matcher.group(1));if(value==null)throw new IllegalArgumentException("Notification variable '"+matcher.group(1)+"' is required by the template.");matcher.appendReplacement(rendered,Matcher.quoteReplacement(value));}matcher.appendTail(rendered);return rendered.toString();}
    private String safeMessage(RuntimeException exception){String message=exception.getMessage();return message==null||message.isBlank()?exception.getClass().getSimpleName():message.substring(0,Math.min(message.length(),1000));}
    private NotificationTemplate template(UUID id){return templates.findById(id).orElseThrow(()->new NoSuchElementException("Notification template was not found."));}
    private NotificationRequest request(UUID id){return requests.findById(id).orElseThrow(()->new NoSuchElementException("Notification request was not found."));}
    private TemplateSummary summary(NotificationTemplate value){return new TemplateSummary(value.getId(),value.getCode(),value.getTemplateVersion(),value.getName(),value.getEventType(),value.getChannel(),value.getCategory(),value.getLocale(),value.getSubjectTemplate(),value.getBodyTemplate(),value.getStatus(),value.getPreparedByUserId(),value.getApprovedByUserId(),value.getApprovedAt(),value.getApprovalReason(),value.getVersion());}
    private ConsentSummary summary(NotificationConsent value){return new ConsentSummary(value.getId(),value.getRecipientUserId(),value.getRecipientKey(),value.getChannel(),value.getCategory(),value.getStatus(),value.getSource(),value.getEvidenceReference(),value.getEffectiveFrom(),value.getVersion());}
    private RequestSummary summary(NotificationRequest value){return new RequestSummary(value.getId(),value.getRequestNumber(),value.getIdempotencyKey(),value.getSourceService(),value.getSourceEventId(),value.getEventType(),value.getTemplateCode(),value.getTemplateVersion(),value.getChannel(),value.getCategory(),value.getRecipientUserId(),value.getRecipientKey(),value.getRecipientAddress(),value.getSubject(),value.getBody(),value.getPriority(),value.getStatus(),value.getConsentDecision(),value.getScheduledAt(),value.getNextAttemptAt(),value.getAttemptCount(),value.getMaxAttempts(),value.getProviderCode(),value.getProviderMessageId(),value.getProviderDeliveryStatus(),value.getProviderStatusAt(),value.getProviderStatusDetail(),value.getSentAt(),value.getFailedAt(),value.getLastErrorCode(),value.getLastErrorMessage(),value.getManualRetryByUserId(),value.getManualRetryAt(),value.getManualRetryReason(),value.getVersion());}
    private AttemptSummary summary(NotificationDeliveryAttempt value){return new AttemptSummary(value.getId(),value.getNotificationRequestId(),value.getAttemptNumber(),value.getProviderCode(),value.getStartedAt(),value.getCompletedAt(),value.getOutcome(),value.getProviderMessageId(),value.getErrorCode(),value.getErrorMessage(),value.getResponseMetadata());}
    private InboxSummary summary(NotificationEventInbox value){return new InboxSummary(value.getId(),value.getSourceService(),value.getSourceEventId(),value.getEventType(),value.getReceivedAt(),value.getProcessedAt(),value.getStatus(),value.getProcessingError(),value.getAttemptCount(),value.getMaxAttempts(),value.getNextAttemptAt(),value.getLastAttemptAt(),value.getManualRetryByUserId(),value.getManualRetryAt(),value.getManualRetryReason(),value.getVersion());}
    private CallbackSummary summary(NotificationProviderCallback value){return new CallbackSummary(value.getId(),value.getProviderCode(),value.getProviderEventId(),value.getProviderMessageId(),value.getDeliveryStatus(),value.getOccurredAt(),value.getReceivedAt(),value.getNotificationRequestId(),value.getErrorCode(),value.getErrorMessage());}
    private InAppSummary summary(InAppNotification value){return new InAppSummary(value.getId(),value.getNotificationRequestId(),value.getRecipientUserId(),value.getRecipientKey(),value.getTitle(),value.getBody(),value.getDeliveredAt(),value.getReadAt(),value.getReadByUserId(),value.getVersion());}
    private NotificationRequest.ProviderDeliveryStatus providerStatus(NotificationProviderCallback.DeliveryStatus status){return switch(status){case DELIVERED->NotificationRequest.ProviderDeliveryStatus.DELIVERED;case BOUNCED->NotificationRequest.ProviderDeliveryStatus.BOUNCED;case FAILED->NotificationRequest.ProviderDeliveryStatus.FAILED;};}
}
