package zw.ac.uz.emhare.dining.operations;

import zw.ac.uz.emhare.dining.operations.domain.model.DiningWorkflowEvent;
import zw.ac.uz.emhare.dining.operations.domain.model.MealAttendanceEvent;
import zw.ac.uz.emhare.dining.operations.domain.model.MealAttendanceReversal;
import zw.ac.uz.emhare.dining.operations.domain.model.MealServiceSession;
import zw.ac.uz.emhare.dining.operations.domain.model.StudentDietaryRequirement;
import zw.ac.uz.emhare.dining.operations.domain.model.StudentDiningAssignment;
import zw.ac.uz.emhare.dining.operations.infrastructure.persistence.DiningWorkflowEventRepository;
import zw.ac.uz.emhare.dining.operations.infrastructure.persistence.MealAttendanceEventRepository;
import zw.ac.uz.emhare.dining.operations.infrastructure.persistence.MealAttendanceReversalRepository;
import zw.ac.uz.emhare.dining.operations.infrastructure.persistence.MealServiceSessionRepository;
import zw.ac.uz.emhare.dining.operations.infrastructure.persistence.OperationalDiningHallRepository;
import zw.ac.uz.emhare.dining.operations.infrastructure.persistence.OperationalDiningPlanMealRepository;
import zw.ac.uz.emhare.dining.operations.infrastructure.persistence.OperationalDiningPlanRepository;
import zw.ac.uz.emhare.dining.operations.infrastructure.persistence.OperationalMealOptionRepository;
import zw.ac.uz.emhare.dining.operations.infrastructure.persistence.StudentDietaryRequirementRepository;
import zw.ac.uz.emhare.dining.operations.infrastructure.persistence.StudentDiningAssignmentRepository;
import zw.ac.uz.emhare.dining.setup.domain.model.DiningHall;
import zw.ac.uz.emhare.dining.setup.domain.model.DiningPlan;
import zw.ac.uz.emhare.dining.setup.domain.model.DiningPlanMeal;
import zw.ac.uz.emhare.dining.setup.domain.model.MealOption;

import java.time.*;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import zw.ac.uz.emhare.dining.operations.api.model.DiningOperationsApiModels.*;
import zw.ac.uz.emhare.dining.setup.*;

/** @author Tinashe K */
@Service
public class DiningOperationsService {
    private final OperationalDiningHallRepository halls; private final OperationalDiningPlanRepository plans;
    private final OperationalMealOptionRepository options; private final OperationalDiningPlanMealRepository planMeals;
    private final StudentDiningAssignmentRepository assignments; private final StudentDietaryRequirementRepository dietary;
    private final MealServiceSessionRepository sessions; private final MealAttendanceEventRepository attendance;
    private final MealAttendanceReversalRepository reversals; private final DiningWorkflowEventRepository workflow;
    private final Clock clock;
    public DiningOperationsService(OperationalDiningHallRepository halls,OperationalDiningPlanRepository plans,OperationalMealOptionRepository options,OperationalDiningPlanMealRepository planMeals,StudentDiningAssignmentRepository assignments,StudentDietaryRequirementRepository dietary,MealServiceSessionRepository sessions,MealAttendanceEventRepository attendance,MealAttendanceReversalRepository reversals,DiningWorkflowEventRepository workflow,Clock clock){this.halls=halls;this.plans=plans;this.options=options;this.planMeals=planMeals;this.assignments=assignments;this.dietary=dietary;this.sessions=sessions;this.attendance=attendance;this.reversals=reversals;this.workflow=workflow;this.clock=clock;}
    @Transactional(readOnly=true) public OperationsRegister register(){return new OperationsRegister(
        assignments.findAllByDeletedAtIsNullOrderByEffectiveFromDesc().stream().map(this::view).toList(),
        dietary.findAllByDeletedAtIsNullOrderByStudentNumberAscRequirementCodeAsc().stream().map(this::view).toList(),
        sessions.findAllByDeletedAtIsNullOrderByServiceDateDescScheduledOpensAtDesc().stream().map(this::view).toList(),
        attendance.findAllByDeletedAtIsNullOrderByCapturedAtDesc().stream().map(this::view).toList(),
        reversals.findAllByDeletedAtIsNullOrderByReversedAtDesc().stream().map(this::view).toList(),
        workflow.findAllByDeletedAtIsNullOrderByOccurredAtDesc().stream().map(this::view).toList(),
        attendance.statistics().stream().map(item->new AttendanceStatisticSummary(item.getDimension(),item.getGroupCode(),item.getAdmitted(),item.getDenied(),item.getReversed(),item.getNetAdmitted())).toList());}
    @Transactional public AssignmentSummary prepareAssignment(PrepareAssignment c,UUID actor){long sequence=assignments.nextNumber();StudentDiningAssignment item=assignments.saveAndFlush(new StudentDiningAssignment("DINE-%08d".formatted(sequence),c.studentId(),c.studentNumber(),c.studentName(),c.academicPeriodId(),c.academicPeriodCode(),c.programmeCode(),c.studentGroupCode(),hall(c.diningHallId()),plan(c.diningPlanId()),c.accommodationAllocationId(),c.effectiveFrom(),c.effectiveUntil(),actor));record(DiningWorkflowEvent.AggregateType.DINING_ASSIGNMENT,item.getId(),null,"DRAFT","PREPARED","Dining assignment prepared",actor);return view(item);}
    @Transactional public AssignmentSummary assignmentAction(UUID id,String action,AssignmentAction c,UUID actor){StudentDiningAssignment item=assignment(id);String before=item.getStatus().name();Instant now=clock.instant();switch(action){case "activate"->item.activate(actor,c.reason(),now,c.expectedVersion());case "suspend"->item.suspend(c.reason(),c.expectedVersion());case "resume"->item.resume(c.reason(),c.expectedVersion());case "end"->item.end(StudentDiningAssignment.Status.ENDED,actor,c.reason(),now,c.expectedVersion());case "cancel"->item.end(StudentDiningAssignment.Status.CANCELLED,actor,c.reason(),now,c.expectedVersion());default->throw new IllegalArgumentException("Unsupported dining assignment action.");}assignments.saveAndFlush(item);record(DiningWorkflowEvent.AggregateType.DINING_ASSIGNMENT,item.getId(),before,item.getStatus().name(),action,c.reason(),actor);return view(item);}
    @Transactional public DietarySummary recordDietary(RecordDietaryRequirement c,UUID actor){StudentDietaryRequirement item=dietary.saveAndFlush(new StudentDietaryRequirement(c.studentId(),c.studentNumber(),c.requirementCode(),c.description(),c.severity(),c.clinicalDocumentId(),c.effectiveFrom(),c.effectiveUntil(),actor));record(DiningWorkflowEvent.AggregateType.DIETARY_REQUIREMENT,item.getId(),null,"ACTIVE","RECORDED",c.description(),actor);return view(item);}
    @Transactional public DietarySummary resolveDietary(UUID id,ResolveDietaryRequirement c,UUID actor){StudentDietaryRequirement item=dietary.findById(id).orElseThrow(()->new IllegalArgumentException("Dietary requirement was not found."));String before=item.getStatus().name();item.resolve(c.targetStatus(),actor,c.reason(),clock.instant(),c.expectedVersion());dietary.saveAndFlush(item);record(DiningWorkflowEvent.AggregateType.DIETARY_REQUIREMENT,id,before,item.getStatus().name(),c.targetStatus().name(),c.reason(),actor);return view(item);}
    @Transactional public SessionSummary planSession(PlanMealSession c,UUID actor){long sequence=sessions.nextNumber();MealServiceSession item=sessions.saveAndFlush(new MealServiceSession("SESSION-%08d".formatted(sequence),hall(c.diningHallId()),option(c.mealOptionId()),c.serviceDate(),c.scheduledOpensAt(),c.scheduledClosesAt(),c.expectedServings(),actor));record(DiningWorkflowEvent.AggregateType.MEAL_SESSION,item.getId(),null,"PLANNED","PLANNED","Meal service session planned",actor);return view(item);}
    @Transactional public SessionSummary sessionAction(UUID id,String action,SessionAction c,UUID actor){MealServiceSession item=session(id);String before=item.getStatus().name();Instant now=clock.instant();switch(action){case "open"->item.open(actor,now,c.expectedVersion());case "close"->item.close(actor,now,c.expectedVersion());default->throw new IllegalArgumentException("Unsupported meal session action.");}sessions.saveAndFlush(item);record(DiningWorkflowEvent.AggregateType.MEAL_SESSION,id,before,item.getStatus().name(),action,c.reason(),actor);return view(item);}
    @Transactional public SessionSummary reconcileSession(UUID id,ReconcileSession c,UUID actor){MealServiceSession item=session(id);String before=item.getStatus().name();item.reconcile(actor,c.countedServings(),c.reason(),clock.instant(),c.expectedVersion());sessions.saveAndFlush(item);record(DiningWorkflowEvent.AggregateType.MEAL_SESSION,id,before,item.getStatus().name(),"RECONCILED",c.reason(),actor);return view(item);}
    @Transactional public AttendanceSummary captureAttendance(CaptureAttendance c,UUID actor){Optional<MealAttendanceEvent> existing=attendance.findByIdempotencyKey(c.idempotencyKey());if(existing.isPresent())return view(existing.get());MealServiceSession session=session(c.sessionId());LocalDate date=session.getServiceDate();Optional<StudentDiningAssignment> assignment=assignments.findFirstByStudentIdAndDiningHallIdAndStatusAndEffectiveFromLessThanEqualAndEffectiveUntilGreaterThanEqual(c.studentId(),session.getDiningHall().getId(),StudentDiningAssignment.Status.ACTIVE,date,date);MealAttendanceEvent.Outcome outcome=MealAttendanceEvent.Outcome.DENIED;String code="NO_ACTIVE_ASSIGNMENT";String reason="Student has no active dining assignment for this hall and service date.";StudentDiningAssignment entitled=null;if(assignment.isPresent()){StudentDiningAssignment candidate=assignment.get();Optional<DiningPlanMeal> entitlement=planMeals.findByDiningPlanIdAndMealOptionId(candidate.getDiningPlan().getId(),session.getMealOption().getId());if(entitlement.isPresent()&&servesOn(entitlement.get(),date)){outcome=MealAttendanceEvent.Outcome.ADMITTED;code=null;reason=null;entitled=candidate;}else{code="MEAL_NOT_IN_PLAN";reason="The active dining plan does not include this meal on the service day.";}}long sequence=attendance.nextNumber();MealAttendanceEvent item=attendance.saveAndFlush(new MealAttendanceEvent("MEAL-%08d".formatted(sequence),session,entitled,c.studentId(),c.studentNumber(),c.studentName(),outcome,code,reason,actor,clock.instant(),c.captureChannel(),c.deviceId(),c.idempotencyKey()));return view(item);}
    @Transactional public ReversalSummary reverseAttendance(UUID id,ReverseAttendance c,UUID actor){MealAttendanceEvent event=attendance.findById(id).orElseThrow(()->new IllegalArgumentException("Meal attendance event was not found."));if(reversals.existsByEventId(id))throw new IllegalStateException("This meal attendance event has already been reversed.");return view(reversals.saveAndFlush(new MealAttendanceReversal(event,c.reasonCode(),c.reason(),actor,clock.instant())));}
    private boolean servesOn(DiningPlanMeal meal,LocalDate date){return switch(date.getDayOfWeek()){case MONDAY->meal.isMonday();case TUESDAY->meal.isTuesday();case WEDNESDAY->meal.isWednesday();case THURSDAY->meal.isThursday();case FRIDAY->meal.isFriday();case SATURDAY->meal.isSaturday();case SUNDAY->meal.isSunday();};}
    private void record(DiningWorkflowEvent.AggregateType type,UUID id,String before,String after,String event,String reason,UUID actor){workflow.saveAndFlush(new DiningWorkflowEvent(type,id,before,after,event,reason,actor,clock.instant()));}
    private DiningHall hall(UUID id){return halls.findById(id).orElseThrow(()->new IllegalArgumentException("Dining hall was not found."));} private DiningPlan plan(UUID id){return plans.findById(id).orElseThrow(()->new IllegalArgumentException("Dining plan was not found."));} private MealOption option(UUID id){return options.findById(id).orElseThrow(()->new IllegalArgumentException("Meal option was not found."));} private StudentDiningAssignment assignment(UUID id){return assignments.findById(id).orElseThrow(()->new IllegalArgumentException("Dining assignment was not found."));} private MealServiceSession session(UUID id){return sessions.findById(id).orElseThrow(()->new IllegalArgumentException("Meal service session was not found."));}
    private AssignmentSummary view(StudentDiningAssignment e){return new AssignmentSummary(e.getId(),e.getAssignmentNumber(),e.getStudentId(),e.getStudentNumber(),e.getStudentName(),e.getAcademicPeriodId(),e.getAcademicPeriodCode(),e.getProgrammeCode(),e.getStudentGroupCode(),e.getDiningHall().getId(),e.getDiningHall().getCode(),e.getDiningPlan().getId(),e.getDiningPlan().getCode(),e.getAccommodationAllocationId(),e.getEffectiveFrom(),e.getEffectiveUntil(),e.getStatus(),e.getPreparedByUserId(),e.getApprovedByUserId(),e.getApprovedAt(),e.getApprovalReason(),e.getEndedByUserId(),e.getEndedAt(),e.getEndReason(),e.getBillingStatus(),e.getVersion());}
    private DietarySummary view(StudentDietaryRequirement e){return new DietarySummary(e.getId(),e.getStudentId(),e.getStudentNumber(),e.getRequirementCode(),e.getDescription(),e.getSeverity(),e.getClinicalDocumentId(),e.getEffectiveFrom(),e.getEffectiveUntil(),e.getStatus(),e.getRecordedByUserId(),e.getResolvedByUserId(),e.getResolvedAt(),e.getResolutionReason(),e.getVersion());}
    private SessionSummary view(MealServiceSession e){return new SessionSummary(e.getId(),e.getSessionNumber(),e.getDiningHall().getId(),e.getDiningHall().getCode(),e.getMealOption().getId(),e.getMealOption().getCode(),e.getServiceDate(),e.getScheduledOpensAt(),e.getScheduledClosesAt(),e.getStatus(),e.getPreparedByUserId(),e.getOpenedByUserId(),e.getOpenedAt(),e.getClosedByUserId(),e.getClosedAt(),e.getReconciledByUserId(),e.getReconciledAt(),e.getReconciliationReason(),e.getExpectedServings(),e.getCountedServings(),attendance.netAdmitted(e.getId()),e.getVersion());}
    private AttendanceSummary view(MealAttendanceEvent e){return new AttendanceSummary(e.getId(),e.getEventNumber(),e.getSession().getId(),e.getSession().getSessionNumber(),e.getAssignment()==null?null:e.getAssignment().getId(),e.getStudentId(),e.getStudentNumber(),e.getStudentName(),e.getOutcome(),e.getDenialReasonCode(),e.getDenialReason(),e.getCapturedByUserId(),e.getCapturedAt(),e.getCaptureChannel(),e.getDeviceId(),e.getIdempotencyKey(),reversals.existsByEventId(e.getId()));}
    private ReversalSummary view(MealAttendanceReversal e){return new ReversalSummary(e.getId(),e.getEvent().getId(),e.getEvent().getEventNumber(),e.getReasonCode(),e.getReason(),e.getReversedByUserId(),e.getReversedAt());}
    private WorkflowEventSummary view(DiningWorkflowEvent e){return new WorkflowEventSummary(e.getId(),e.getAggregateType(),e.getAggregateId(),e.getPreviousState(),e.getNewState(),e.getEventType(),e.getReason(),e.getActorUserId(),e.getOccurredAt());}
}
