CREATE TABLE admission_cycles (
    id uuid PRIMARY KEY,
    academic_year_id uuid NOT NULL,
    intake_id uuid NOT NULL,
    code varchar(50) NOT NULL,
    name varchar(200) NOT NULL,
    opens_at timestamptz NOT NULL,
    closes_at timestamptz NOT NULL,
    status varchar(30) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL,
    CONSTRAINT uk_admission_cycles_code UNIQUE (code)
);

CREATE TABLE application_types (
    id uuid PRIMARY KEY,
    code varchar(50) NOT NULL,
    name varchar(150) NOT NULL,
    requires_employment_history boolean NOT NULL,
    requires_referees boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL,
    CONSTRAINT uk_application_types_code UNIQUE (code)
);

CREATE TABLE application_fees (
    id uuid PRIMARY KEY,
    application_type_id uuid NOT NULL REFERENCES application_types (id),
    applicant_category_code varchar(30) NOT NULL,
    currency_code varchar(3) NOT NULL,
    amount numeric(12, 2) NOT NULL,
    effective_from date NOT NULL,
    effective_to date,
    is_active boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL
);

CREATE TABLE applicants (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL,
    applicant_number varchar(40) NOT NULL,
    applicant_category_code varchar(30) NOT NULL,
    title_code varchar(30),
    first_name varchar(100) NOT NULL,
    middle_names varchar(150),
    last_name varchar(100) NOT NULL,
    date_of_birth date,
    gender_code varchar(30),
    marital_status_code varchar(30),
    national_id_number varchar(50),
    passport_number varchar(50),
    country_id uuid,
    nationality_country_id uuid,
    place_of_birth varchar(150),
    disability_status_code varchar(30),
    special_needs varchar(1000),
    sponsor_type_code varchar(30),
    primary_email varchar(200) NOT NULL,
    primary_phone varchar(50),
    postal_address varchar(500),
    residential_address varchar(500),
    legacy_applicants_detail_id bigint,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL,
    CONSTRAINT uk_applicants_user_id UNIQUE (user_id),
    CONSTRAINT uk_applicants_applicant_number UNIQUE (applicant_number)
);

CREATE TABLE applications (
    id uuid PRIMARY KEY,
    admission_cycle_id uuid NOT NULL REFERENCES admission_cycles (id),
    applicant_id uuid NOT NULL REFERENCES applicants (id),
    application_type_id uuid NOT NULL REFERENCES application_types (id),
    application_number varchar(50) NOT NULL,
    submitted_at timestamptz,
    payment_required boolean NOT NULL,
    payment_confirmed_at timestamptz,
    payment_override_by_user_id uuid,
    payment_override_reason varchar(500),
    status varchar(30) NOT NULL,
    status_reason varchar(1000),
    verified_by_user_id uuid,
    verified_at timestamptz,
    legacy_statu_id bigint,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL,
    CONSTRAINT uk_applications_application_number UNIQUE (application_number)
);

CREATE UNIQUE INDEX uk_applications_active_cycle_applicant_type
    ON applications (admission_cycle_id, applicant_id, application_type_id)
    WHERE deleted_at IS NULL AND status NOT IN ('WITHDRAWN', 'DECLINED', 'CONVERTED');

CREATE TABLE application_status_events (
    id uuid PRIMARY KEY,
    application_id uuid NOT NULL REFERENCES applications (id),
    from_status varchar(30),
    to_status varchar(30) NOT NULL,
    reason varchar(1000),
    changed_by_user_id uuid NOT NULL,
    changed_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL
);

CREATE TABLE application_programme_choices (
    id uuid PRIMARY KEY,
    application_id uuid NOT NULL REFERENCES applications (id),
    programme_id uuid NOT NULL,
    choice_rank integer NOT NULL,
    choice_status varchar(30) NOT NULL,
    evaluation_summary varchar(1000),
    decision_reason varchar(1000),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL,
    CONSTRAINT uk_application_choice_rank UNIQUE (application_id, choice_rank),
    CONSTRAINT uk_application_choice_programme UNIQUE (application_id, programme_id)
);

CREATE TABLE application_documents (
    id uuid PRIMARY KEY,
    application_id uuid NOT NULL REFERENCES applications (id),
    document_id uuid NOT NULL,
    requirement_code varchar(80) NOT NULL,
    is_required boolean NOT NULL,
    status varchar(30) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL,
    CONSTRAINT uk_application_documents_requirement UNIQUE (application_id, requirement_code, document_id)
);

CREATE TABLE exam_bodies (
    id uuid PRIMARY KEY,
    code varchar(50) NOT NULL,
    name varchar(150) NOT NULL,
    country_id uuid,
    is_active boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL,
    CONSTRAINT uk_exam_bodies_code UNIQUE (code)
);

CREATE TABLE admission_subjects (
    id uuid PRIMARY KEY,
    code varchar(50) NOT NULL,
    name varchar(150) NOT NULL,
    level varchar(30) NOT NULL,
    subject_group_code varchar(50),
    is_active boolean NOT NULL,
    legacy_olevel_subject_code varchar(50),
    legacy_subject_code varchar(50),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL,
    CONSTRAINT uk_admission_subjects_level_code UNIQUE (level, code)
);

CREATE TABLE applicant_qualification_sittings (
    id uuid PRIMARY KEY,
    application_id uuid NOT NULL REFERENCES applications (id),
    level varchar(30) NOT NULL,
    exam_body_id uuid REFERENCES exam_bodies (id),
    institution_name varchar(200),
    centre_number varchar(50),
    candidate_number varchar(50),
    year_written integer,
    country_id uuid,
    document_id uuid,
    legacy_source_table varchar(100),
    legacy_source_id bigint,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL
);

CREATE TABLE applicant_qualification_results (
    id uuid PRIMARY KEY,
    qualification_sitting_id uuid NOT NULL REFERENCES applicant_qualification_sittings (id),
    subject_id uuid REFERENCES admission_subjects (id),
    subject_name_snapshot varchar(150) NOT NULL,
    grade varchar(20) NOT NULL,
    mark numeric(8, 2),
    points numeric(8, 2),
    is_principal_subject boolean,
    result_status varchar(30) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL
);

CREATE UNIQUE INDEX uk_qualification_results_sitting_subject
    ON applicant_qualification_results (qualification_sitting_id, subject_id)
    WHERE subject_id IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE admission_requirement_sets (
    id uuid PRIMARY KEY,
    programme_id uuid NOT NULL,
    application_type_id uuid NOT NULL REFERENCES application_types (id),
    admission_cycle_id uuid REFERENCES admission_cycles (id),
    version_code varchar(50) NOT NULL,
    effective_from date NOT NULL,
    effective_to date,
    status varchar(30) NOT NULL,
    minimum_total_points numeric(8, 2),
    male_cutoff_points numeric(8, 2),
    female_cutoff_points numeric(8, 2),
    requires_english boolean NOT NULL,
    advanced_rules_json jsonb,
    advanced_rules_version varchar(30),
    approved_by_user_id uuid,
    approved_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL,
    CONSTRAINT uk_requirement_set_version UNIQUE (programme_id, application_type_id, admission_cycle_id, version_code)
);

CREATE TABLE admission_subject_requirements (
    id uuid PRIMARY KEY,
    requirement_set_id uuid NOT NULL REFERENCES admission_requirement_sets (id),
    level varchar(30) NOT NULL,
    subject_id uuid REFERENCES admission_subjects (id),
    subject_group_code varchar(50),
    requirement_type varchar(30) NOT NULL,
    minimum_grade varchar(20),
    minimum_points numeric(8, 2),
    minimum_count integer,
    weight numeric(8, 2),
    sort_order integer NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL
);

CREATE TABLE application_evaluations (
    id uuid PRIMARY KEY,
    application_id uuid NOT NULL REFERENCES applications (id),
    programme_choice_id uuid NOT NULL REFERENCES application_programme_choices (id),
    requirement_set_id uuid NOT NULL REFERENCES admission_requirement_sets (id),
    status varchar(40) NOT NULL,
    total_points numeric(8, 2),
    rank_score numeric(10, 4),
    missing_requirements_json jsonb,
    rule_results_json jsonb,
    evaluated_at timestamptz NOT NULL,
    evaluated_by_user_id uuid,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL,
    CONSTRAINT uk_application_evaluations_choice_requirement UNIQUE (programme_choice_id, requirement_set_id)
);

CREATE TABLE application_payment_references (
    id uuid PRIMARY KEY,
    application_id uuid NOT NULL REFERENCES applications (id),
    reference varchar(80) NOT NULL,
    amount_due numeric(12, 2) NOT NULL,
    currency_code varchar(3) NOT NULL,
    base_currency_code varchar(3) NOT NULL DEFAULT 'USD',
    exchange_rate_id uuid,
    base_amount_due numeric(12, 2),
    status varchar(30) NOT NULL,
    required_for_submission boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL,
    CONSTRAINT uk_application_payment_references_reference UNIQUE (reference)
);

CREATE TABLE application_accommodation_requests (
    id uuid PRIMARY KEY,
    application_id uuid NOT NULL REFERENCES applications (id),
    status varchar(30) NOT NULL,
    preferred_campus_code varchar(50),
    special_requirements varchar(1000),
    notes varchar(1000),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL,
    CONSTRAINT uk_application_accommodation_requests_application UNIQUE (application_id)
);

CREATE TABLE application_exam_arrangements (
    id uuid PRIMARY KEY,
    application_id uuid NOT NULL REFERENCES applications (id),
    programme_choice_id uuid,
    exam_type_code varchar(50) NOT NULL,
    status varchar(30) NOT NULL,
    scheduled_at timestamptz,
    exam_session_id uuid,
    score numeric(8, 2),
    outcome_code varchar(50),
    notes varchar(1000),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint NOT NULL
);

CREATE TABLE admission_cycles_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    academic_year_id uuid,
    intake_id uuid,
    code varchar(50),
    name varchar(200),
    opens_at timestamptz,
    closes_at timestamptz,
    status varchar(30),
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE application_types_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    code varchar(50),
    name varchar(150),
    requires_employment_history boolean,
    requires_referees boolean,
    is_active boolean,
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE application_fees_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    application_type_id uuid,
    applicant_category_code varchar(30),
    currency_code varchar(3),
    amount numeric(12, 2),
    effective_from date,
    effective_to date,
    is_active boolean,
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE applicants_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    user_id uuid,
    applicant_number varchar(40),
    applicant_category_code varchar(30),
    title_code varchar(30),
    first_name varchar(100),
    middle_names varchar(150),
    last_name varchar(100),
    date_of_birth date,
    gender_code varchar(30),
    marital_status_code varchar(30),
    national_id_number varchar(50),
    passport_number varchar(50),
    country_id uuid,
    nationality_country_id uuid,
    place_of_birth varchar(150),
    disability_status_code varchar(30),
    special_needs varchar(1000),
    sponsor_type_code varchar(30),
    primary_email varchar(200),
    primary_phone varchar(50),
    postal_address varchar(500),
    residential_address varchar(500),
    legacy_applicants_detail_id bigint,
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE applications_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    admission_cycle_id uuid,
    applicant_id uuid,
    application_type_id uuid,
    application_number varchar(50),
    submitted_at timestamptz,
    payment_required boolean,
    payment_confirmed_at timestamptz,
    payment_override_by_user_id uuid,
    payment_override_reason varchar(500),
    status varchar(30),
    status_reason varchar(1000),
    verified_by_user_id uuid,
    verified_at timestamptz,
    legacy_statu_id bigint,
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE application_status_events_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    application_id uuid,
    from_status varchar(30),
    to_status varchar(30),
    reason varchar(1000),
    changed_by_user_id uuid,
    changed_at timestamptz,
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE application_programme_choices_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    application_id uuid,
    programme_id uuid,
    choice_rank integer,
    choice_status varchar(30),
    evaluation_summary varchar(1000),
    decision_reason varchar(1000),
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE application_documents_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    application_id uuid,
    document_id uuid,
    requirement_code varchar(80),
    is_required boolean,
    status varchar(30),
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE exam_bodies_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    code varchar(50),
    name varchar(150),
    country_id uuid,
    is_active boolean,
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE admission_subjects_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    code varchar(50),
    name varchar(150),
    level varchar(30),
    subject_group_code varchar(50),
    is_active boolean,
    legacy_olevel_subject_code varchar(50),
    legacy_subject_code varchar(50),
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE applicant_qualification_sittings_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    application_id uuid,
    level varchar(30),
    exam_body_id uuid,
    institution_name varchar(200),
    centre_number varchar(50),
    candidate_number varchar(50),
    year_written integer,
    country_id uuid,
    document_id uuid,
    legacy_source_table varchar(100),
    legacy_source_id bigint,
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE applicant_qualification_results_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    qualification_sitting_id uuid,
    subject_id uuid,
    subject_name_snapshot varchar(150),
    grade varchar(20),
    mark numeric(8, 2),
    points numeric(8, 2),
    is_principal_subject boolean,
    result_status varchar(30),
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE admission_requirement_sets_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    programme_id uuid,
    application_type_id uuid,
    admission_cycle_id uuid,
    version_code varchar(50),
    effective_from date,
    effective_to date,
    status varchar(30),
    minimum_total_points numeric(8, 2),
    male_cutoff_points numeric(8, 2),
    female_cutoff_points numeric(8, 2),
    requires_english boolean,
    advanced_rules_json jsonb,
    advanced_rules_version varchar(30),
    approved_by_user_id uuid,
    approved_at timestamptz,
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE admission_subject_requirements_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    requirement_set_id uuid,
    level varchar(30),
    subject_id uuid,
    subject_group_code varchar(50),
    requirement_type varchar(30),
    minimum_grade varchar(20),
    minimum_points numeric(8, 2),
    minimum_count integer,
    weight numeric(8, 2),
    sort_order integer,
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE application_evaluations_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    application_id uuid,
    programme_choice_id uuid,
    requirement_set_id uuid,
    status varchar(40),
    total_points numeric(8, 2),
    rank_score numeric(10, 4),
    missing_requirements_json jsonb,
    rule_results_json jsonb,
    evaluated_at timestamptz,
    evaluated_by_user_id uuid,
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE application_payment_references_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    application_id uuid,
    reference varchar(80),
    amount_due numeric(12, 2),
    currency_code varchar(3),
    base_currency_code varchar(3),
    exchange_rate_id uuid,
    base_amount_due numeric(12, 2),
    status varchar(30),
    required_for_submission boolean,
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE application_accommodation_requests_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    application_id uuid,
    status varchar(30),
    preferred_campus_code varchar(50),
    special_requirements varchar(1000),
    notes varchar(1000),
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE application_exam_arrangements_aud (
    id uuid NOT NULL,
    rev integer NOT NULL REFERENCES revinfo (rev),
    revtype smallint,
    application_id uuid,
    programme_choice_id uuid,
    exam_type_code varchar(50),
    status varchar(30),
    scheduled_at timestamptz,
    exam_session_id uuid,
    score numeric(8, 2),
    outcome_code varchar(50),
    notes varchar(1000),
    created_at timestamptz,
    updated_at timestamptz,
    created_by_user_id uuid,
    modified_by_user_id uuid,
    deleted_at timestamptz,
    deleted_by_user_id uuid,
    version bigint,
    PRIMARY KEY (id, rev)
);
