spring:
  datasource:
    hikari:
      maximum-pool-size: ${EMHARE_DATABASE_MAXIMUM_POOL_SIZE:5}
      minimum-idle: ${EMHARE_DATABASE_MINIMUM_IDLE:1}
      connection-timeout: ${EMHARE_DATABASE_CONNECTION_TIMEOUT_MILLISECONDS:5000}
      validation-timeout: ${EMHARE_DATABASE_VALIDATION_TIMEOUT_MILLISECONDS:2000}
      idle-timeout: ${EMHARE_DATABASE_IDLE_TIMEOUT_MILLISECONDS:300000}
      max-lifetime: ${EMHARE_DATABASE_MAX_LIFETIME_MILLISECONDS:1500000}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        envers:
          audit_table_suffix: _aud
          revision_field_name: rev
          revision_type_field_name: revtype
  flyway:
    enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    publisher-confirm-type: simple
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1s
          max-attempts: 5
          max-interval: 10s
          multiplier: 2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:http://localhost:8099/realms/emhare}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-components: when-authorized
      show-details: when-authorized
      roles: system-admin

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
