package zw.ac.uz.emhare.notifications;

import static org.junit.jupiter.api.Assertions.*;
import java.sql.*;
import java.util.*;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.*;
import org.testcontainers.junit.jupiter.*;
import org.testcontainers.postgresql.PostgreSQLContainer;

/** @author Tinashe K */
@Testcontainers
class NotificationMigrationTest {
    @Container static final PostgreSQLContainer postgres=new PostgreSQLContainer("postgres:18-alpine").withDatabaseName("emhare_notifications_migration").withUsername("emhare_service").withPassword("emhare_test_password");
    private Connection connection;
    @BeforeAll static void migrate(){Flyway.configure().dataSource(postgres.getJdbcUrl(),postgres.getUsername(),postgres.getPassword()).locations("classpath:db/migration").load().migrate();}
    @BeforeEach void connect() throws SQLException{connection=DriverManager.getConnection(postgres.getJdbcUrl(),postgres.getUsername(),postgres.getPassword());}
    @AfterEach void close() throws SQLException{connection.close();}
    @Test void createsGovernedBusinessAndAuditTables() throws SQLException{for(String table:List.of("notification_templates","notification_consents","notification_requests","notification_delivery_attempts","notification_event_inbox","notification_provider_callbacks","in_app_notifications")){assertTrue(tableExists(table));assertTrue(tableExists(table+"_aud"));assertStandardColumns(table);}}
    @Test void deliveryAttemptEvidenceIsAppendOnly() throws SQLException{UUID template=UUID.randomUUID(),request=UUID.randomUUID(),attempt=UUID.randomUUID(),maker=UUID.randomUUID();execute("INSERT INTO notification_templates(id,code,template_version,name,event_type,channel,category,locale,body_template,status,prepared_by_user_id,created_at,updated_at,version) VALUES (?,'TEST',1,'Test','TEST','EMAIL','TRANSACTIONAL','en-ZW','Body','DRAFT',?,now(),now(),0)",template,maker);execute("INSERT INTO notification_requests(id,request_number,idempotency_key,source_service,event_type,template_id,template_code,template_version,channel,category,recipient_key,recipient_address,body,priority,status,consent_decision,scheduled_at,next_attempt_at,max_attempts,created_at,updated_at,version) VALUES (?,'NTF-1','key-1','TEST','TEST',?,'TEST',1,'EMAIL','TRANSACTIONAL','person','person@example.test','Body','NORMAL','QUEUED','NOT_REQUIRED',now(),now(),5,now(),now(),0)",request,template);execute("INSERT INTO notification_delivery_attempts(id,notification_request_id,attempt_number,provider_code,started_at,completed_at,outcome,provider_message_id,created_at,updated_at,version) VALUES (?,?,1,'TEST',now(),now(),'SENT','provider-1',now(),now(),0)",attempt,request);SQLException error=assertThrows(SQLException.class,()->execute("DELETE FROM notification_delivery_attempts WHERE id=?",attempt));assertEquals("P0001",error.getSQLState());}
    @Test void providerCallbackEvidenceRequiresJsonObjectAndIsImmutable() throws SQLException{UUID callback=UUID.randomUUID();SQLException invalidPayload=assertThrows(SQLException.class,()->execute("INSERT INTO notification_provider_callbacks(id,provider_code,provider_event_id,provider_message_id,delivery_status,occurred_at,received_at,callback_payload,created_at,updated_at,version) VALUES (?,'TEST','event-invalid','message-invalid','FAILED',now(),now(),'\"scalar\"'::jsonb,now(),now(),0)",callback));assertEquals("23514",invalidPayload.getSQLState());UUID validCallback=UUID.randomUUID();execute("INSERT INTO notification_provider_callbacks(id,provider_code,provider_event_id,provider_message_id,delivery_status,occurred_at,received_at,callback_payload,created_at,updated_at,version) VALUES (?,'TEST','event-valid','message-valid','DELIVERED',now(),now(),'{}'::jsonb,now(),now(),0)",validCallback);SQLException immutable=assertThrows(SQLException.class,()->execute("UPDATE notification_provider_callbacks SET error_message='changed' WHERE id=?",validCallback));assertEquals("P0001",immutable.getSQLState());}
    @Test void seedsApprovedEmailAndInAppTemplatesForRequiredWorkflowEvents() throws SQLException{try(PreparedStatement statement=connection.prepareStatement("SELECT event_type, count(*) FROM notification_templates WHERE status='ACTIVE' GROUP BY event_type");ResultSet result=statement.executeQuery()){Map<String,Integer> templateCounts=new HashMap<>();while(result.next())templateCounts.put(result.getString(1),result.getInt(2));for(String eventType:List.of("APPLICATION_SUBMITTED","MISSING_DOCUMENTS","PAYMENT_CONFIRMED","VERIFICATION_DECISION","OFFER_DISPATCHED","OFFER_RESPONSE","STUDENT_CONVERSION","REGISTRATION_ACTION","WORKFLOW_TASK"))assertEquals(2,templateCounts.get(eventType));}}
    @Test void seedsActiveRefereeReferenceRequestEmailTemplate() throws SQLException{try(PreparedStatement statement=connection.prepareStatement("SELECT count(*) FROM notification_templates WHERE code='REFEREE_REFERENCE_REQUEST_EMAIL' AND event_type='REFEREE_REFERENCE_REQUEST' AND channel='EMAIL' AND status='ACTIVE' AND body_template LIKE '%{{responseUrl}}%'");ResultSet result=statement.executeQuery()){result.next();assertEquals(1,result.getInt(1));}}
    private boolean tableExists(String name)throws SQLException{try(PreparedStatement statement=connection.prepareStatement("SELECT to_regclass(?) IS NOT NULL")){statement.setString(1,"public."+name);try(ResultSet result=statement.executeQuery()){result.next();return result.getBoolean(1);}}}
    private void assertStandardColumns(String table)throws SQLException{Set<String> actual=new HashSet<>();try(PreparedStatement statement=connection.prepareStatement("SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=?")){statement.setString(1,table);try(ResultSet result=statement.executeQuery()){while(result.next())actual.add(result.getString(1));}}assertTrue(actual.containsAll(Set.of("id","created_at","updated_at","created_by_user_id","modified_by_user_id","deleted_at","deleted_by_user_id","version")));}
    private void execute(String sql,Object... values)throws SQLException{try(PreparedStatement statement=connection.prepareStatement(sql)){for(int index=0;index<values.length;index++)statement.setObject(index+1,values[index]);statement.executeUpdate();}}
}
