export type NotificationChannel = "EMAIL" | "SMS" | "IN_APP";
export type NotificationCategory = "TRANSACTIONAL" | "WORKFLOW" | "SECURITY" | "MARKETING";
export type NotificationTemplateStatus = "DRAFT" | "ACTIVE" | "RETIRED";
export type NotificationRequestStatus = "QUEUED" | "PROCESSING" | "SENT" | "RETRY_SCHEDULED" | "FAILED" | "SUPPRESSED" | "CANCELLED";
export type NotificationProviderDeliveryStatus = "ACCEPTED" | "DELIVERED" | "BOUNCED" | "FAILED";

export interface NotificationTemplateSummary { id:string;code:string;templateVersion:number;name:string;eventType:string;channel:NotificationChannel;category:NotificationCategory;locale:string;subjectTemplate:string|null;bodyTemplate:string;status:NotificationTemplateStatus;preparedByUserId:string;approvedByUserId:string|null;approvedAt:string|null;approvalReason:string|null;version:number }
export interface NotificationConsentSummary { id:string;recipientUserId:string|null;recipientKey:string;channel:NotificationChannel;category:NotificationCategory;status:"OPTED_IN"|"OPTED_OUT"|"NOT_REQUIRED";source:string;evidenceReference:string|null;effectiveFrom:string;version:number }
export interface NotificationRequestSummary { id:string;requestNumber:string;idempotencyKey:string;sourceService:string;sourceEventId:string|null;eventType:string;templateCode:string;templateVersion:number;channel:NotificationChannel;category:NotificationCategory;recipientUserId:string|null;recipientKey:string;recipientAddress:string;subject:string|null;body:string;priority:"LOW"|"NORMAL"|"HIGH"|"URGENT";status:NotificationRequestStatus;consentDecision:string;scheduledAt:string;nextAttemptAt:string|null;attemptCount:number;maxAttempts:number;providerCode:string|null;providerMessageId:string|null;providerDeliveryStatus:NotificationProviderDeliveryStatus|null;providerStatusAt:string|null;providerStatusDetail:string|null;sentAt:string|null;failedAt:string|null;lastErrorCode:string|null;lastErrorMessage:string|null;manualRetryByUserId:string|null;manualRetryAt:string|null;manualRetryReason:string|null;version:number }
export interface NotificationDeliveryAttemptSummary { id:string;notificationRequestId:string;attemptNumber:number;providerCode:string;startedAt:string;completedAt:string;outcome:"SENT"|"RETRYABLE_FAILURE"|"PERMANENT_FAILURE";providerMessageId:string|null;errorCode:string|null;errorMessage:string|null;responseMetadata:Record<string,unknown> }
export interface NotificationEventInboxSummary { id:string;sourceService:string;sourceEventId:string;eventType:string;receivedAt:string;processedAt:string|null;status:"RECEIVED"|"PROCESSING"|"PROCESSED"|"RETRY_SCHEDULED"|"DEAD";processingError:string|null;attemptCount:number;maxAttempts:number;nextAttemptAt:string|null;lastAttemptAt:string|null;manualRetryByUserId:string|null;manualRetryAt:string|null;manualRetryReason:string|null;version:number }
export interface NotificationProviderCallbackSummary { id:string;providerCode:string;providerEventId:string;providerMessageId:string;deliveryStatus:"DELIVERED"|"BOUNCED"|"FAILED";occurredAt:string;receivedAt:string;notificationRequestId:string;errorCode:string|null;errorMessage:string|null }
export interface InAppNotificationSummary { id:string;notificationRequestId:string;recipientUserId:string;recipientKey:string;title:string|null;body:string;deliveredAt:string;readAt:string|null;readByUserId:string|null;version:number }
export interface NotificationRegister { templates:NotificationTemplateSummary[];consents:NotificationConsentSummary[];requests:NotificationRequestSummary[];deliveryAttempts:NotificationDeliveryAttemptSummary[];eventInbox:NotificationEventInboxSummary[];providerCallbacks:NotificationProviderCallbackSummary[];inAppNotifications:InAppNotificationSummary[] }
