-- Author: Tinashe K
-- Governed public Communications content, workflow, publication, media, events, and reads.

CREATE TABLE revinfo (
  rev integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revtstmp bigint NOT NULL,
  actor_user_id uuid,
  service_name varchar(100) NOT NULL,
  correlation_id varchar(100),
  reason varchar(500)
);

CREATE TABLE communication_categories (
  id uuid PRIMARY KEY,
  code varchar(80) NOT NULL UNIQUE,
  name varchar(160) NOT NULL,
  description varchar(500),
  display_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  created_by_user_id uuid,
  modified_by_user_id uuid,
  deleted_at timestamptz,
  deleted_by_user_id uuid,
  version bigint NOT NULL DEFAULT 0,
  CONSTRAINT ck_communication_category_delete_pair CHECK ((deleted_at IS NULL) = (deleted_by_user_id IS NULL))
);

CREATE TABLE communication_items (
  id uuid PRIMARY KEY,
  category_id uuid REFERENCES communication_categories(id),
  kind varchar(20) NOT NULL,
  slug varchar(180) NOT NULL,
  lifecycle_status varchar(20) NOT NULL DEFAULT 'ACTIVE',
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  created_by_user_id uuid,
  modified_by_user_id uuid,
  deleted_at timestamptz,
  deleted_by_user_id uuid,
  version bigint NOT NULL DEFAULT 0,
  CONSTRAINT ck_communication_item_kind CHECK (kind IN ('NEWS','NOTICE','ALERT','CAMPAIGN','LINK','EVENT')),
  CONSTRAINT ck_communication_item_status CHECK (lifecycle_status IN ('ACTIVE','ARCHIVED')),
  CONSTRAINT ck_communication_item_slug CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  CONSTRAINT ck_communication_item_delete_pair CHECK ((deleted_at IS NULL) = (deleted_by_user_id IS NULL))
);
CREATE UNIQUE INDEX uk_communication_item_active_slug ON communication_items (lower(slug)) WHERE deleted_at IS NULL;

CREATE TABLE communication_media_assets (
  id uuid PRIMARY KEY,
  storage_key varchar(500) NOT NULL UNIQUE,
  original_file_name varchar(255) NOT NULL,
  content_type varchar(100) NOT NULL,
  size_bytes bigint NOT NULL,
  checksum_sha256 varchar(64) NOT NULL,
  alternative_text varchar(500) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'READY',
  uploaded_by_user_id uuid NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  created_by_user_id uuid,
  modified_by_user_id uuid,
  deleted_at timestamptz,
  deleted_by_user_id uuid,
  version bigint NOT NULL DEFAULT 0,
  CONSTRAINT ck_communication_media_type CHECK (content_type IN ('image/jpeg','image/png','image/webp','application/pdf')),
  CONSTRAINT ck_communication_media_size CHECK (size_bytes > 0),
  CONSTRAINT ck_communication_media_alt CHECK (length(trim(alternative_text)) > 0),
  CONSTRAINT ck_communication_media_status CHECK (status IN ('READY','QUARANTINED','RETIRED')),
  CONSTRAINT ck_communication_media_delete_pair CHECK ((deleted_at IS NULL) = (deleted_by_user_id IS NULL))
);

CREATE TABLE communication_item_versions (
  id uuid PRIMARY KEY,
  item_id uuid NOT NULL REFERENCES communication_items(id),
  version_number integer NOT NULL,
  title varchar(240) NOT NULL,
  summary varchar(600) NOT NULL,
  schema_version integer NOT NULL DEFAULT 1,
  structured_content jsonb NOT NULL,
  workflow_status varchar(20) NOT NULL DEFAULT 'DRAFT',
  authored_by_user_id uuid NOT NULL,
  submitted_by_user_id uuid,
  submitted_at timestamptz,
  decided_by_user_id uuid,
  decided_at timestamptz,
  decision_reason varchar(1000),
  hero_media_asset_id uuid REFERENCES communication_media_assets(id),
  external_url varchar(1000),
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  created_by_user_id uuid,
  modified_by_user_id uuid,
  deleted_at timestamptz,
  deleted_by_user_id uuid,
  version bigint NOT NULL DEFAULT 0,
  CONSTRAINT uk_communication_item_version UNIQUE (item_id, version_number),
  CONSTRAINT ck_communication_version_number CHECK (version_number > 0),
  CONSTRAINT ck_communication_schema_version CHECK (schema_version = 1),
  CONSTRAINT ck_communication_content_array CHECK (jsonb_typeof(structured_content) = 'array'),
  CONSTRAINT ck_communication_workflow_status CHECK (workflow_status IN ('DRAFT','IN_REVIEW','APPROVED','REJECTED')),
  CONSTRAINT ck_communication_submission_pair CHECK ((submitted_at IS NULL) = (submitted_by_user_id IS NULL)),
  CONSTRAINT ck_communication_decision_pair CHECK ((decided_at IS NULL) = (decided_by_user_id IS NULL)),
  CONSTRAINT ck_communication_version_delete_pair CHECK ((deleted_at IS NULL) = (deleted_by_user_id IS NULL))
);

CREATE TABLE event_occurrences (
  id uuid PRIMARY KEY,
  communication_version_id uuid NOT NULL UNIQUE REFERENCES communication_item_versions(id),
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  timezone varchar(80) NOT NULL,
  attendance_mode varchar(20) NOT NULL,
  venue_name varchar(240),
  address varchar(500),
  online_url varchar(1000),
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  created_by_user_id uuid,
  modified_by_user_id uuid,
  deleted_at timestamptz,
  deleted_by_user_id uuid,
  version bigint NOT NULL DEFAULT 0,
  CONSTRAINT ck_event_occurrence_window CHECK (ends_at > starts_at),
  CONSTRAINT ck_event_attendance_mode CHECK (attendance_mode IN ('IN_PERSON','ONLINE','HYBRID')),
  CONSTRAINT ck_event_location CHECK ((attendance_mode = 'IN_PERSON' AND venue_name IS NOT NULL) OR (attendance_mode = 'ONLINE' AND online_url IS NOT NULL) OR (attendance_mode = 'HYBRID' AND venue_name IS NOT NULL AND online_url IS NOT NULL)),
  CONSTRAINT ck_event_occurrence_delete_pair CHECK ((deleted_at IS NULL) = (deleted_by_user_id IS NULL))
);

CREATE TABLE communication_publications (
  id uuid PRIMARY KEY,
  item_id uuid NOT NULL REFERENCES communication_items(id),
  version_id uuid NOT NULL REFERENCES communication_item_versions(id),
  status varchar(20) NOT NULL,
  publish_from timestamptz NOT NULL,
  publish_until timestamptz,
  pinned boolean NOT NULL DEFAULT false,
  featured boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL DEFAULT 0,
  withdrawn_at timestamptz,
  withdrawn_by_user_id uuid,
  withdrawal_reason varchar(1000),
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  created_by_user_id uuid,
  modified_by_user_id uuid,
  deleted_at timestamptz,
  deleted_by_user_id uuid,
  version bigint NOT NULL DEFAULT 0,
  CONSTRAINT ck_communication_publication_status CHECK (status IN ('SCHEDULED','LIVE','EXPIRED','WITHDRAWN')),
  CONSTRAINT ck_communication_publication_window CHECK (publish_until IS NULL OR publish_until > publish_from),
  CONSTRAINT ck_communication_withdrawal_pair CHECK ((withdrawn_at IS NULL AND withdrawn_by_user_id IS NULL AND withdrawal_reason IS NULL) OR (withdrawn_at IS NOT NULL AND withdrawn_by_user_id IS NOT NULL AND length(trim(withdrawal_reason)) > 0)),
  CONSTRAINT ck_communication_publication_delete_pair CHECK ((deleted_at IS NULL) = (deleted_by_user_id IS NULL))
);
CREATE INDEX ix_communication_publication_window ON communication_publications (publish_from, publish_until) WHERE deleted_at IS NULL AND status <> 'WITHDRAWN';

CREATE TABLE communication_workflow_events (
  id uuid PRIMARY KEY,
  item_id uuid NOT NULL REFERENCES communication_items(id),
  version_id uuid NOT NULL REFERENCES communication_item_versions(id),
  event_type varchar(40) NOT NULL,
  from_status varchar(20),
  to_status varchar(20) NOT NULL,
  actor_user_id uuid NOT NULL,
  reason varchar(1000),
  occurred_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  created_by_user_id uuid,
  modified_by_user_id uuid,
  deleted_at timestamptz,
  deleted_by_user_id uuid,
  version bigint NOT NULL DEFAULT 0,
  CONSTRAINT ck_communication_workflow_target CHECK (to_status IN ('DRAFT','IN_REVIEW','APPROVED','REJECTED')),
  CONSTRAINT ck_communication_workflow_delete_pair CHECK ((deleted_at IS NULL) = (deleted_by_user_id IS NULL))
);

CREATE TABLE communication_read_receipts (
  id uuid PRIMARY KEY,
  publication_id uuid NOT NULL REFERENCES communication_publications(id),
  reader_user_id uuid NOT NULL,
  read_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  created_by_user_id uuid,
  modified_by_user_id uuid,
  deleted_at timestamptz,
  deleted_by_user_id uuid,
  version bigint NOT NULL DEFAULT 0,
  CONSTRAINT uk_communication_read_receipt UNIQUE (publication_id, reader_user_id),
  CONSTRAINT ck_communication_read_delete_pair CHECK ((deleted_at IS NULL) = (deleted_by_user_id IS NULL))
);

CREATE FUNCTION protect_approved_communication_version() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.workflow_status = 'APPROVED' THEN
    RAISE EXCEPTION 'Approved communication versions are immutable';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_protect_approved_communication_version BEFORE UPDATE OR DELETE ON communication_item_versions FOR EACH ROW EXECUTE FUNCTION protect_approved_communication_version();

CREATE FUNCTION protect_communication_workflow_event() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Communication workflow events are append-only';
END $$;
CREATE TRIGGER trg_protect_communication_workflow_event BEFORE UPDATE OR DELETE ON communication_workflow_events FOR EACH ROW EXECUTE FUNCTION protect_communication_workflow_event();

-- Envers audit tables mirror every business entity.
CREATE TABLE communication_categories_aud (LIKE communication_categories INCLUDING DEFAULTS);
CREATE TABLE communication_items_aud (LIKE communication_items INCLUDING DEFAULTS);
CREATE TABLE communication_item_versions_aud (LIKE communication_item_versions INCLUDING DEFAULTS);
CREATE TABLE communication_publications_aud (LIKE communication_publications INCLUDING DEFAULTS);
CREATE TABLE communication_workflow_events_aud (LIKE communication_workflow_events INCLUDING DEFAULTS);
CREATE TABLE communication_media_assets_aud (LIKE communication_media_assets INCLUDING DEFAULTS);
CREATE TABLE event_occurrences_aud (LIKE event_occurrences INCLUDING DEFAULTS);
CREATE TABLE communication_read_receipts_aud (LIKE communication_read_receipts INCLUDING DEFAULTS);

DO $$
DECLARE audit_table text;
BEGIN
  FOREACH audit_table IN ARRAY ARRAY['communication_categories_aud','communication_items_aud','communication_item_versions_aud','communication_publications_aud','communication_workflow_events_aud','communication_media_assets_aud','event_occurrences_aud','communication_read_receipts_aud']
  LOOP
    EXECUTE format('ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I', audit_table, replace(audit_table, '_aud', '') || '_pkey');
    EXECUTE format('ALTER TABLE %I ADD COLUMN rev integer NOT NULL REFERENCES revinfo(rev)', audit_table);
    EXECUTE format('ALTER TABLE %I ADD COLUMN revtype smallint', audit_table);
    EXECUTE format('ALTER TABLE %I ADD PRIMARY KEY (id, rev)', audit_table);
  END LOOP;
END $$;

INSERT INTO communication_categories (id, code, name, description, display_order, active, created_at, updated_at, version)
VALUES
  ('30000000-0000-4000-8000-000000000001', 'GENERAL', 'General', 'Institution-wide public information.', 10, true, now(), now(), 0),
  ('30000000-0000-4000-8000-000000000002', 'ACADEMIC', 'Academic', 'Public academic information; canonical academic dates remain owned by Academic Setup.', 20, true, now(), now(), 0),
  ('30000000-0000-4000-8000-000000000003', 'STUDENT_LIFE', 'Student life', 'Public campus and student-life information.', 30, true, now(), now(), 0);
