package zw.ac.uz.emhare.finance.billing;

import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import zw.ac.uz.emhare.finance.billing.FinanceBillingContracts.*;
import zw.ac.uz.emhare.finance.catalogue.FinanceFeePricingResolver;
import zw.ac.uz.emhare.finance.catalogue.FinanceFeePricingResolver.PricingScope;
import zw.ac.uz.emhare.finance.catalogue.FinanceFeeCatalogue;
import zw.ac.uz.emhare.finance.catalogue.FinanceFeeRuleScope;
import zw.ac.uz.emhare.finance.catalogue.FinanceStudentDiscountContracts.ResolveDiscount;
import zw.ac.uz.emhare.finance.catalogue.GovernedFinanceStudentDiscountService;
import zw.ac.uz.emhare.finance.payment.FinanceReferenceGenerator;
import zw.ac.uz.emhare.finance.student.*;
import zw.ac.uz.emhare.common.messaging.*;

/** Approval-controlled billing events and atomic immutable invoice posting. @author Tinashe K */
@Service
public class GovernedFinanceBillingService {
    private final FinanceBillingEventRepository eventRepository;private final FinanceBillingEventScopeRepository scopeRepository;
    private final FinanceInvoiceRepository invoiceRepository;private final FinanceInvoiceLineRepository lineRepository;
    private final FinanceBillingPolicyRepository policyRepository;
    private final StudentFinanceAccountRepository accountRepository;private final FinanceFeePricingResolver pricingResolver;
    private final GovernedFinanceStudentDiscountService studentDiscountService;
    private final FinanceReferenceGenerator referenceGenerator;private final Clock clock;
    public GovernedFinanceBillingService(FinanceBillingEventRepository eventRepository,FinanceBillingEventScopeRepository scopeRepository,
            FinanceInvoiceRepository invoiceRepository,FinanceInvoiceLineRepository lineRepository,FinanceBillingPolicyRepository policyRepository,
            StudentFinanceAccountRepository accountRepository,FinanceFeePricingResolver pricingResolver,
            GovernedFinanceStudentDiscountService studentDiscountService,FinanceReferenceGenerator referenceGenerator,Clock clock){this.eventRepository=eventRepository;this.scopeRepository=scopeRepository;this.invoiceRepository=invoiceRepository;this.lineRepository=lineRepository;this.policyRepository=policyRepository;this.accountRepository=accountRepository;this.pricingResolver=pricingResolver;this.studentDiscountService=studentDiscountService;this.referenceGenerator=referenceGenerator;this.clock=clock;}

    @Transactional(readOnly=true) public BillingRegister register(){return new BillingRegister(policyRepository.findAllByDeletedAtIsNullOrderByCodeAscPolicyVersionDesc().stream().map(this::policyView).toList(),eventRepository.findAllByDeletedAtIsNullOrderBySubmittedAtDescEventNumberDesc().stream().map(this::eventView).toList(),invoiceRepository.findAllByDeletedAtIsNullOrderByPostedAtDescInvoiceNumberDesc().stream().map(this::invoiceView).toList());}
    @Transactional public BillingPolicySummary createPolicy(CreateBillingPolicy command,UUID actor){int version=policyRepository.findFirstByCodeIgnoreCaseAndDeletedAtIsNullOrderByPolicyVersionDesc(command.code()).map(policy->policy.getPolicyVersion()+1).orElse(1);FinanceFeeCatalogue catalogue=pricingResolver.requireActiveCatalogue(command.feeCatalogueId());FinanceBillingPolicy policy=new FinanceBillingPolicy(command.code(),version,command.name(),command.sourceEventType(),catalogue,command.lineBasis(),command.quantityBasis(),command.fixedQuantity(),command.effectiveFrom(),command.effectiveUntil(),actor);return policyView(policyRepository.saveAndFlush(policy));}
    @Transactional public BillingPolicySummary movePolicy(UUID id,String action,BillingDecision command,UUID actor){FinanceBillingPolicy policy=policyRepository.findLockedByIdAndDeletedAtIsNull(id).orElseThrow(()->new IllegalArgumentException("Billing policy was not found."));if("activate".equals(action))policy.activate(actor,clock.instant(),command.reason(),command.expectedVersion());else if("retire".equals(action))policy.retire(actor,clock.instant(),command.reason(),command.expectedVersion());else throw new IllegalArgumentException("Unsupported billing-policy action.");return policyView(policyRepository.saveAndFlush(policy));}
    @Transactional public BillingEventSummary create(CreateBillingEvent command,UUID actor){
        eventRepository.findBySourceServiceAndSourceEventIdAndSourceLineReferenceAndDeletedAtIsNull(command.sourceService().trim(),command.sourceEventId(),command.sourceLineReference().trim()).ifPresent(existing->{throw new IllegalStateException("This authoritative source line has already produced billing event "+existing.getEventNumber()+".");});
        StudentFinanceAccount account=accountRepository.findByIdAndDeletedAtIsNull(command.studentFinanceAccountId()).orElseThrow(()->new IllegalArgumentException("Student finance account was not found."));
        List<PricingScope> scopes=command.scopes().stream().map(scope->new PricingScope(scope.scopeDimension(),scope.referenceId(),scope.referenceCode(),scope.referenceName())).toList();
        FinanceFeePricingResolver.ResolvedPrice price=pricingResolver.resolve(command.feeCatalogueId(),command.effectiveAt(),scopes);Instant now=clock.instant();
        UUID programmeId=referenceId(command.scopes(),FinanceFeeRuleScope.Dimension.PROGRAMME);
        UUID academicUnitId=referenceId(command.scopes(),FinanceFeeRuleScope.Dimension.ACADEMIC_UNIT);
        UUID programmeLevelId=referenceId(command.scopes(),FinanceFeeRuleScope.Dimension.PROGRAMME_LEVEL);
        String programmeLevelCode=referenceCode(command.scopes(),FinanceFeeRuleScope.Dimension.PROGRAMME_LEVEL);
        Integer programmePeriodNumber=programmePeriodNumber(command.scopes());
        var discount=programmeId==null||academicUnitId==null||programmeLevelId==null||programmeLevelCode==null||programmePeriodNumber==null
                ?Optional.<zw.ac.uz.emhare.finance.catalogue.FinanceStudentDiscountContracts.AppliedDiscount>empty()
                :studentDiscountService.resolve(new ResolveDiscount(command.feeCatalogueId(),programmeId,academicUnitId,
                        programmeLevelId,programmeLevelCode,programmeStudyLevel(programmePeriodNumber),command.effectiveAt()));
        FinanceBillingEvent event=new FinanceBillingEvent(referenceGenerator.nextBillingEventNumber(),command.sourceService(),command.sourceEventType(),command.sourceEventId(),command.sourceAggregateType(),command.sourceAggregateId(),command.sourceLineReference(),account,price.catalogue(),price.rule(),command.description(),command.quantity(),command.effectiveAt(),discount.orElse(null),actor,now);
        try{eventRepository.saveAndFlush(event);scopeRepository.saveAllAndFlush(scopes.stream().map(scope->new FinanceBillingEventScope(event,scope)).toList());}
        catch(DataIntegrityViolationException exception){throw new IllegalStateException("Billing source or pricing evidence conflicts with an existing controlled record.",exception);}
        return eventView(event);
    }
    @Transactional public BillingEventSummary decide(UUID id,boolean approve,BillingDecision command,UUID actor){FinanceBillingEvent event=requireEvent(id);event.decide(approve,actor,clock.instant(),command.reason(),command.expectedVersion());return eventView(eventRepository.saveAndFlush(event));}
    @Transactional public InvoiceSummary post(PostInvoice command,UUID actor){
        List<UUID> requestedIds=command.billingEventIds().stream().distinct().sorted().toList();if(requestedIds.size()!=command.billingEventIds().size())throw new IllegalArgumentException("Each approved billing event can appear only once in an invoice request.");
        List<FinanceBillingEvent> events=requestedIds.stream().map(this::requireEvent).toList();FinanceBillingEvent first=events.getFirst();
        if(events.stream().anyMatch(event->event.getStatus()!=FinanceBillingEvent.Status.APPROVED))throw new IllegalStateException("Every selected billing event must be independently approved and not previously invoiced.");
        if(events.stream().anyMatch(event->!event.getStudentFinanceAccount().getId().equals(first.getStudentFinanceAccount().getId())))throw new IllegalArgumentException("One invoice can contain billing events for only one student finance account.");
        if(events.stream().anyMatch(event->!event.getTransactionCurrencyCode().equals(first.getTransactionCurrencyCode())))throw new IllegalArgumentException("One invoice can contain billing events in only one transaction currency.");
        BigDecimal grossTransactionTotal=events.stream().map(FinanceBillingEvent::getGrossTransactionAmount).reduce(BigDecimal.ZERO,BigDecimal::add);
        BigDecimal transactionDiscountTotal=events.stream().map(FinanceBillingEvent::getTransactionDiscountAmount).reduce(BigDecimal.ZERO,BigDecimal::add);
        BigDecimal netTransactionTotal=events.stream().map(FinanceBillingEvent::getTransactionAmount).reduce(BigDecimal.ZERO,BigDecimal::add);
        BigDecimal grossBaseTotal=events.stream().map(FinanceBillingEvent::getGrossBaseAmount).reduce(BigDecimal.ZERO,BigDecimal::add);
        BigDecimal baseDiscountTotal=events.stream().map(FinanceBillingEvent::getBaseDiscountAmount).reduce(BigDecimal.ZERO,BigDecimal::add);
        BigDecimal netBaseTotal=events.stream().map(FinanceBillingEvent::getBaseAmount).reduce(BigDecimal.ZERO,BigDecimal::add);Instant postedAt=clock.instant();
        FinanceInvoice invoice=invoiceRepository.saveAndFlush(new FinanceInvoice(referenceGenerator.nextInvoiceNumber(),first.getStudentFinanceAccount(),first.getTransactionCurrencyCode(),grossTransactionTotal,transactionDiscountTotal,netTransactionTotal,grossBaseTotal,baseDiscountTotal,netBaseTotal,command.invoiceDate(),command.dueDate(),actor,postedAt,command.postingReason()));
        List<FinanceInvoiceLine> lines=new ArrayList<>();for(int index=0;index<events.size();index++)lines.add(new FinanceInvoiceLine(invoice,index+1,events.get(index)));
        lineRepository.saveAllAndFlush(lines);events.forEach(event->event.markInvoiced(postedAt));eventRepository.saveAllAndFlush(events);return invoiceView(invoice);
    }
    @Transactional public List<BillingEventSummary> importConfirmedRegistration(StudentRegistrationConfirmedEvent registration,UUID integrationActor){
        if(registration.schemaVersion()!=StudentRegistrationConfirmedEvent.CURRENT_SCHEMA_VERSION)throw new IllegalArgumentException("Unsupported confirmed-registration schema version.");
        List<FinanceBillingPolicy> policies=policyRepository.findActivePolicies(EmhareMessagingTopology.STUDENT_REGISTRATION_CONFIRMED_EVENT,registration.occurredAt());
        if(policies.isEmpty())throw new IllegalStateException("No active Finance billing policy covers confirmed registrations at this effective time.");
        StudentFinanceAccount account=accountRepository.findByStudentIdAndDeletedAtIsNull(registration.studentId()).orElseThrow(()->new IllegalStateException("Confirmed registration has no student finance account."));
        List<BillingEventSummary> created=new ArrayList<>();for(FinanceBillingPolicy policy:policies){if(policy.getLineBasis()==FinanceBillingPolicy.LineBasis.REGISTRATION){created.add(create(registrationCommand(registration,account,policy,null),integrationActor));}else{for(StudentRegistrationConfirmedEvent.RegisteredModule module:registration.modules())created.add(create(registrationCommand(registration,account,policy,module),integrationActor));}}
        return created;
    }
    private CreateBillingEvent registrationCommand(StudentRegistrationConfirmedEvent registration,StudentFinanceAccount account,FinanceBillingPolicy policy,StudentRegistrationConfirmedEvent.RegisteredModule module){List<BillingScopeInput> scopes=new ArrayList<>();scopes.add(new BillingScopeInput(FinanceFeeRuleScope.Dimension.ACADEMIC_PERIOD,registration.academicPeriodId(),registration.academicPeriodCode(),registration.academicPeriodName()));scopes.add(new BillingScopeInput(FinanceFeeRuleScope.Dimension.ACADEMIC_UNIT,registration.owningAcademicUnitId(),registration.owningAcademicUnitCode(),registration.owningAcademicUnitName()));scopes.add(new BillingScopeInput(FinanceFeeRuleScope.Dimension.PROGRAMME_LEVEL,registration.programmeLevelId(),registration.programmeLevelCode(),registration.programmeLevelName()));scopes.add(new BillingScopeInput(FinanceFeeRuleScope.Dimension.PROGRAMME,registration.programmeId(),null,"Programme "+registration.programmeId()));scopes.add(new BillingScopeInput(FinanceFeeRuleScope.Dimension.PROGRAMME_PERIOD,null,String.valueOf(registration.programmePeriodNumber()),"Programme study level "+programmeStudyLevel(registration.programmePeriodNumber())));if(module!=null)scopes.add(new BillingScopeInput(FinanceFeeRuleScope.Dimension.MODULE,module.moduleId(),module.moduleCode(),module.moduleName()));String lineReference=policy.getCode()+":V"+policy.getPolicyVersion()+":"+(module==null?"REGISTRATION":module.registrationModuleId());String description=policy.getName()+(module==null?"":" · "+module.moduleCode()+" · "+module.moduleName());BigDecimal quantity=policy.quantityForModule(module==null?null:module.creditValue());return new CreateBillingEvent("student-records-service",EmhareMessagingTopology.STUDENT_REGISTRATION_CONFIRMED_EVENT,registration.eventId(),"REGISTRATION",registration.registrationSessionId(),lineReference,account.getId(),policy.getFeeCatalogue().getId(),description,quantity,registration.occurredAt(),scopes);}
    private UUID referenceId(List<BillingScopeInput> scopes,FinanceFeeRuleScope.Dimension dimension){return scopes.stream().filter(scope -> scope.scopeDimension()==dimension).map(BillingScopeInput::referenceId).filter(Objects::nonNull).findFirst().orElse(null);}
    private String referenceCode(List<BillingScopeInput> scopes,FinanceFeeRuleScope.Dimension dimension){return scopes.stream().filter(scope -> scope.scopeDimension()==dimension).map(BillingScopeInput::referenceCode).filter(Objects::nonNull).findFirst().orElse(null);}
    private Integer programmePeriodNumber(List<BillingScopeInput> scopes){return scopes.stream().filter(scope -> scope.scopeDimension()==FinanceFeeRuleScope.Dimension.PROGRAMME_PERIOD).map(BillingScopeInput::referenceCode).filter(Objects::nonNull).findFirst().map(value->{try{return Integer.valueOf(value);}catch(NumberFormatException exception){throw new IllegalArgumentException("Programme-period scope code must be a positive number.");}}).orElse(null);}
    private String programmeStudyLevel(int programmePeriodNumber){if(programmePeriodNumber<1)throw new IllegalArgumentException("Programme period must be positive.");return ((programmePeriodNumber+1)/2)+"."+(((programmePeriodNumber-1)%2)+1);}
    private FinanceBillingEvent requireEvent(UUID id){return eventRepository.findLockedByIdAndDeletedAtIsNull(id).orElseThrow(()->new IllegalArgumentException("Billing event was not found."));}
    private BillingEventSummary eventView(FinanceBillingEvent event){return new BillingEventSummary(event.getId(),event.getEventNumber(),event.getSourceService(),event.getSourceEventType(),event.getSourceEventId(),event.getSourceAggregateType(),event.getSourceAggregateId(),event.getSourceLineReference(),event.getStudentFinanceAccount().getId(),event.getStudentFinanceAccount().getAccountNumber(),event.getStudentId(),event.getStudentNumber(),event.getFeeCatalogue().getId(),event.getFeeCatalogue().getCode(),event.getFeeCatalogue().getName(),event.getFeeRule().getId(),event.getFeeRule().getRuleVersion(),event.getDescription(),event.getQuantity(),event.getTransactionCurrencyCode(),event.getTransactionUnitAmount(),event.getGrossTransactionAmount(),event.getTransactionDiscountAmount(),event.getTransactionAmount(),event.getBaseCurrencyCode(),event.getExchangeRate()==null?null:event.getExchangeRate().getId(),event.getBaseUnitAmount(),event.getGrossBaseAmount(),event.getBaseDiscountAmount(),event.getBaseAmount(),event.getDiscountRuleId(),event.getDiscountRuleCode(),event.getDiscountPercentage(),event.getEffectiveAt(),event.getStatus(),event.getPreparedByUserId(),event.getSubmittedAt(),event.getApprovedByUserId(),event.getApprovedAt(),event.getInvoicedAt(),event.getVersion(),scopeRepository.findAllByBillingEventIdAndDeletedAtIsNullOrderByScopeDimensionAsc(event.getId()).stream().map(scope->new BillingScopeSummary(scope.getId(),scope.getScopeDimension(),scope.getReferenceId(),scope.getReferenceCode(),scope.getReferenceName())).toList());}
    private InvoiceSummary invoiceView(FinanceInvoice invoice){return new InvoiceSummary(invoice.getId(),invoice.getInvoiceNumber(),invoice.getStudentFinanceAccount().getId(),invoice.getStudentFinanceAccount().getAccountNumber(),invoice.getStudentId(),invoice.getStudentNumber(),invoice.getTransactionCurrencyCode(),invoice.getBaseCurrencyCode(),invoice.getGrossTransactionAmount(),invoice.getTransactionDiscountAmount(),invoice.getNetTransactionAmount(),invoice.getGrossBaseAmount(),invoice.getBaseDiscountAmount(),invoice.getNetBaseAmount(),invoice.getInvoiceDate(),invoice.getDueDate(),invoice.getStatus(),invoice.getPostedByUserId(),invoice.getPostedAt(),invoice.getVersion(),lineRepository.findAllByInvoiceIdAndDeletedAtIsNullOrderByLineNumberAsc(invoice.getId()).stream().map(line->new InvoiceLineSummary(line.getId(),line.getLineNumber(),line.getBillingEvent().getId(),line.getBillingEvent().getEventNumber(),line.getFeeCode(),line.getDescription(),line.getQuantity(),line.getGrossTransactionAmount(),line.getTransactionDiscountAmount(),line.getTransactionAmount(),line.getGrossBaseAmount(),line.getBaseDiscountAmount(),line.getBaseAmount(),line.getDiscountRuleId(),line.getDiscountRuleCode(),line.getDiscountPercentage(),line.getReceivableAccountCode(),line.getRevenueAccountCode())).toList());}
    private BillingPolicySummary policyView(FinanceBillingPolicy policy){return new BillingPolicySummary(policy.getId(),policy.getCode(),policy.getPolicyVersion(),policy.getName(),policy.getSourceEventType(),policy.getFeeCatalogue().getId(),policy.getFeeCatalogue().getCode(),policy.getFeeCatalogue().getName(),policy.getLineBasis(),policy.getQuantityBasis(),policy.getFixedQuantity(),policy.getEffectiveFrom(),policy.getEffectiveUntil(),policy.getStatus(),policy.getPreparedByUserId(),policy.getActivatedByUserId(),policy.getActivatedAt(),policy.getVersion());}
}
